const {onRequest}=require('firebase-functions/v2/https');
const {defineSecret}=require('firebase-functions/params');
const {initializeApp}=require('firebase-admin/app');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
const {getAppCheck}=require('firebase-admin/app-check');
const {dateKeys,canStart,limits,safeContext,systemPrompt}=require('./policy');
initializeApp();
const db=getFirestore(),OPENAI_API_KEY=defineSecret('OPENAI_API_KEY');
const ALLOWED_ORIGINS=new Set(['https://yinonha-rgb.github.io','http://localhost:8000','http://127.0.0.1:8000']);

exports.teacherApi=onRequest({region:'me-west1',secrets:[OPENAI_API_KEY],timeoutSeconds:60,memory:'256MiB',cors:false},async(req,res)=>{
  const origin=req.headers.origin||'';if(ALLOWED_ORIGINS.has(origin)){res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');res.set('Access-Control-Allow-Headers','Authorization, Content-Type, X-Firebase-AppCheck');res.set('Access-Control-Allow-Methods','POST, OPTIONS')}if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST'||!ALLOWED_ORIGINS.has(origin))return res.status(403).json({error:'origin-denied'});
  try{
    const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({error:'unauthorized'});const decoded=await getAuth().verifyIdToken(token,true),uid=decoded.uid;
    if(process.env.REQUIRE_APP_CHECK==='true'){const appCheck=req.headers['x-firebase-appcheck'];if(!appCheck)return res.status(401).json({error:'app-check-required'});await getAppCheck().verifyToken(appCheck)}
    const action=req.body?.action||'session';if(action==='usage')return usage(uid,res);if(action==='complete')return complete(uid,req.body,res);if(action==='delete-transcripts')return deleteTranscripts(uid,res);if(action!=='session')return res.status(400).json({error:'unknown-action'});
    const context=safeContext(req.body?.context);if(!context.lesson.id||!context.child.id)return res.status(400).json({error:'invalid-context'});const consent=await db.doc(`users/${uid}/state/main`).get();if(!consent.exists||consent.data()?.payload?.settings?.teacherAI?.consent!==true||consent.data()?.payload?.settings?.teacherAI?.enabled!==true)return res.status(403).json({error:'parent-consent-required'});
    const configured=limits(req.body?.limits),keys=dateKeys(),usageRef=db.doc(`users/${uid}/teacherUsage/${keys.month}`),rateRef=db.doc(`users/${uid}/teacherRate/${keys.day}`);let sessionId;
    await db.runTransaction(async tx=>{const [usageSnap,rateSnap]=await Promise.all([tx.get(usageRef),tx.get(rateRef)]),u=usageSnap.data()||{},r=rateSnap.data()||{};const decision=canStart({daySessions:r.sessions||0,daySeconds:r.seconds||0,monthSeconds:u.seconds||0},configured);if(!decision.ok){const e=new Error(decision.error);e.code='limit';throw e}sessionId=db.collection(`users/${uid}/teacherSessions`).doc().id;tx.set(rateRef,{sessions:(r.sessions||0)+1,seconds:r.seconds||0,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(usageRef,{seconds:u.seconds||0,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(db.doc(`users/${uid}/teacherSessions/${sessionId}`),{childId:context.child.id,lessonId:context.lesson.id,status:'created',createdAt:FieldValue.serverTimestamp(),retainTranscript:req.body?.retainTranscript===true,contextVersion:1})});
    const apiResponse=await fetch('https://api.openai.com/v1/realtime/client_secrets',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY.value()}`,'Content-Type':'application/json'},body:JSON.stringify({session:{type:'realtime',model:'gpt-realtime',instructions:systemPrompt(context,{hebrewHelp:req.body?.hebrewHelp!==false}),audio:{output:{voice:'marin'}},max_output_tokens:700}})});const out=await apiResponse.json();if(!apiResponse.ok){await db.doc(`users/${uid}/teacherSessions/${sessionId}`).set({status:'credential-error',errorCode:apiResponse.status},{merge:true});return res.status(502).json({error:'realtime-credential-failed'})}const clientSecret=out.value||out.client_secret?.value;if(!clientSecret)return res.status(502).json({error:'missing-client-secret'});return res.json({sessionId,clientSecret,expiresAt:out.expires_at||out.client_secret?.expires_at,limits:configured});
  }catch(e){if(e.code==='limit'||String(e.message).includes('limit'))return res.status(429).json({error:e.message});console.error('teacherApi',e);return res.status(401).json({error:'unauthorized-or-invalid'})}
});

async function usage(uid,res){const keys=dateKeys(),[m,d,state]=await Promise.all([db.doc(`users/${uid}/teacherUsage/${keys.month}`).get(),db.doc(`users/${uid}/teacherRate/${keys.day}`).get(),db.doc(`users/${uid}/state/main`).get()]),configured=limits(state.data()?.payload?.settings?.teacherAI);return res.json({monthSeconds:m.data()?.seconds||0,daySeconds:d.data()?.seconds||0,daySessions:d.data()?.sessions||0,...configured})}
async function complete(uid,body,res){const id=String(body.sessionId||'');if(!/^[A-Za-z0-9_-]{8,80}$/.test(id))return res.status(400).json({error:'invalid-session'});const ref=db.doc(`users/${uid}/teacherSessions/${id}`),snap=await ref.get();if(!snap.exists)return res.status(404).json({error:'not-found'});const duration=Math.min(3600,Math.max(0,Number(body.summary?.durationSeconds)||0)),keys=dateKeys(),retain=snap.data().retainTranscript===true,summary={lessonId:String(body.summary?.lessonId||'').slice(0,80),durationSeconds:duration,phrases:(body.summary?.phrases||[]).slice(0,30),mistakes:(body.summary?.mistakes||[]).slice(0,30),feedback:(body.summary?.feedback||[]).slice(0,20),safetyFlag:body.summary?.safetyFlag===true,transcript:retain?(body.summary?.transcript||[]).slice(0,200):[]};await db.runTransaction(async tx=>{const [m,d]=await Promise.all([tx.get(db.doc(`users/${uid}/teacherUsage/${keys.month}`)),tx.get(db.doc(`users/${uid}/teacherRate/${keys.day}`))]);tx.set(db.doc(`users/${uid}/teacherUsage/${keys.month}`),{seconds:(m.data()?.seconds||0)+duration,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(db.doc(`users/${uid}/teacherRate/${keys.day}`),{seconds:(d.data()?.seconds||0)+duration,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(ref,{status:'completed',completedAt:FieldValue.serverTimestamp(),summary},{merge:true})});return res.json({ok:true})}
async function deleteTranscripts(uid,res){const snaps=await db.collection(`users/${uid}/teacherSessions`).where('retainTranscript','==',true).limit(100).get(),batch=db.batch();snaps.forEach(doc=>batch.update(doc.ref,{'summary.transcript':[],retainTranscript:false,transcriptDeletedAt:FieldValue.serverTimestamp()}));await batch.commit();return res.json({ok:true,count:snaps.size})}
