const PHASES=['greeting','warm-up','teach-vocabulary','listen-repeat','comprehension','speaking','review','summary','goodbye'];
function clamp(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function dateKeys(now=new Date()){const day=now.toISOString().slice(0,10),month=day.slice(0,7);return{day,month}}
function limits(input={}){return{dailyMinutes:clamp(input.dailyMinutes,1,60,15),maxSessionsPerDay:clamp(input.maxSessionsPerDay,1,10,2),monthlyMinutes:clamp(input.monthlyMinutes,1,2000,120)}}
function canStart(usage={},requested={}){const l=limits(requested);if((usage.daySessions||0)>=l.maxSessionsPerDay)return{ok:false,error:'daily-session-limit'};if((usage.daySeconds||0)>=l.dailyMinutes*60)return{ok:false,error:'daily-minute-limit'};if((usage.monthSeconds||0)>=l.monthlyMinutes*60)return{ok:false,error:'monthly-minute-limit'};return{ok:true,limits:l}}
function safeValidation(value={}){return{exerciseId:String(value.exerciseId||'').slice(0,100),kind:value.kind==='sentence'?'sentence':'single-word',expectedAnswers:(value.expectedAnswers||[]).slice(0,12).map(x=>String(x).slice(0,180)),acceptedSynonyms:(value.acceptedSynonyms||[]).slice(0,20).map(x=>String(x).slice(0,180)),pronunciationVariations:(value.pronunciationVariations||[]).slice(0,20).map(x=>String(x).slice(0,180)),recognitionAlternatives:(value.recognitionAlternatives||[]).slice(0,20).map(x=>String(x).slice(0,180)),requiredKeywords:(value.requiredKeywords||[]).slice(0,20).map(x=>String(x).slice(0,60)),keywordMode:value.keywordMode==='any'?'any':'all',minimumThreshold:clamp(value.minimumThreshold,.5,1,.8)}}
function safeContext(input={}){const lesson=input.sharedLesson?.lesson||input.lesson||{},child=input.child||{};return{lesson:{id:String(lesson.id||'').slice(0,80),title:String(lesson.title||'').slice(0,120),titleHe:String(lesson.titleHe||'').slice(0,120),phrases:(lesson.phrases||[]).slice(0,20).map(p=>({english:String(p.english||'').slice(0,180),hebrew:String(p.hebrew||'').slice(0,180),validation:safeValidation(p.validation)})),quiz:(lesson.quiz||[]).slice(0,12).map(q=>({question:String(q.question||'').slice(0,240),expected:String(q.options?.[q.answer]||q.validation?.expectedAnswers?.[0]||'').slice(0,180),validation:safeValidation(q.validation)}))},child:{id:String(child.id||'').slice(0,100),name:String(child.name||'Learner').replace(/[<>]/g,'').slice(0,30),age:clamp(child.age,6,12,null),level:clamp(child.level,1,50,1)},mistakes:(input.mistakes||[]).slice(0,20),completed:(input.completed||[]).slice(0,100),assignment:input.assignment?String(input.assignment).slice(0,300):null}}
function systemPrompt(context,{hebrewHelp=true}={}){const c=safeContext(context),targets=c.lesson.phrases.map(p=>`${p.english} (${p.hebrew}); validation=${JSON.stringify(p.validation)}`).join('; '),answers=c.lesson.quiz.map(q=>`${q.question} => ${q.expected}; validation=${JSON.stringify(q.validation)}`).join('; ');return `You are the English Adventure voice teacher for one child age 6-12. Child first name: ${c.child.name}. Level: ${c.child.level}. Current lesson only: ${c.lesson.title}. Approved vocabulary and validation: ${targets}. Expected answers and authoritative validation contracts: ${answers}. Previous lesson mistakes: ${JSON.stringify(c.mistakes)}. Completed lesson IDs: ${c.completed.join(', ')}. Current assignment: ${c.assignment||'none'}.
Follow every phase in order and do not skip learning goals: ${PHASES.join(' -> ')}. Teach actively: give one brief instruction or question, then wait without interrupting. Primarily use very simple English. ${hebrewHelp?'A short Hebrew hint is allowed only when confusion is clear.':'Do not use Hebrew.'} Praise genuine effort, correct gently, model pronunciation, ask for a repeat when useful, adapt difficulty conservatively, and keep every turn short.
Stay within this lesson and approved educational content. Never ask for an address, school name, phone number, password, private detail, or secrecy. Do not discuss sexual, violent, self-harm, illegal, medical, legal, financial, or age-inappropriate topics. If the child describes a personal-safety concern, respond supportively, encourage speaking with a trusted adult, do not investigate or invent facts, and emit a safety flag for the parent.
Pronunciation judgments must be conservative and framed as observations, never objective scores. Never shame, pressure, or compare the child. Do not claim that audio is stored. At phase changes emit a teacher.phase event; for practice observations emit teacher.assessment. End after the required goodbye or when the parent ends the session.
The frontend deterministic validator is authoritative. Never call an answer correct until a DETERMINISTIC VALIDATOR: APPROVED instruction arrives. An unrelated answer, missing required keyword, low-confidence transcript, silence, noise, or below-threshold result must never receive praise implying correctness. On first rejection say "Not quite. Let's try again." On the second give one small hint. On the third explain the approved answer, ask for one repetition, and continue without an endless loop.`}
module.exports={PHASES,clamp,dateKeys,limits,canStart,safeValidation,safeContext,systemPrompt};
