const PHASES=['greeting','warm-up','teach-vocabulary','listen-repeat','comprehension','speaking','review','summary','goodbye'];
function clamp(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function dateKeys(now=new Date()){const day=now.toISOString().slice(0,10),month=day.slice(0,7);return{day,month}}
function limits(input={}){return{dailyMinutes:clamp(input.dailyMinutes,1,60,15),maxSessionsPerDay:clamp(input.maxSessionsPerDay,1,10,2),monthlyMinutes:clamp(input.monthlyMinutes,1,2000,120)}}
function canStart(usage={},requested={}){const l=limits(requested);if((usage.daySessions||0)>=l.maxSessionsPerDay)return{ok:false,error:'daily-session-limit'};if((usage.daySeconds||0)>=l.dailyMinutes*60)return{ok:false,error:'daily-minute-limit'};if((usage.monthSeconds||0)>=l.monthlyMinutes*60)return{ok:false,error:'monthly-minute-limit'};return{ok:true,limits:l}}
function safeContext(input={}){const lesson=input.lesson||{},child=input.child||{};return{lesson:{id:String(lesson.id||'').slice(0,80),title:String(lesson.title||'').slice(0,120),titleHe:String(lesson.titleHe||'').slice(0,120),phrases:(lesson.phrases||[]).slice(0,20).map(p=>({english:String(p.english||'').slice(0,180),hebrew:String(p.hebrew||'').slice(0,180)})),quiz:(lesson.quiz||[]).slice(0,12).map(q=>({question:String(q.question||'').slice(0,240),expected:String(q.options?.[q.answer]||'').slice(0,180)}))},child:{id:String(child.id||'').slice(0,100),name:String(child.name||'Learner').replace(/[<>]/g,'').slice(0,30),age:clamp(child.age,6,12,null),level:clamp(child.level,1,50,1)},mistakes:(input.mistakes||[]).slice(0,20),completed:(input.completed||[]).slice(0,100),assignment:input.assignment?String(input.assignment).slice(0,300):null}}
function systemPrompt(context,{hebrewHelp=true}={}){const c=safeContext(context),targets=c.lesson.phrases.map(p=>`${p.english} (${p.hebrew})`).join('; '),answers=c.lesson.quiz.map(q=>`${q.question} => ${q.expected}`).join('; ');return `You are the English Adventure voice teacher for one child age 6-12. Child first name: ${c.child.name}. Level: ${c.child.level}. Current lesson only: ${c.lesson.title}. Approved vocabulary: ${targets}. Expected answers: ${answers}. Previous lesson mistakes: ${JSON.stringify(c.mistakes)}. Completed lesson IDs: ${c.completed.join(', ')}. Current assignment: ${c.assignment||'none'}.
Follow every phase in order and do not skip learning goals: ${PHASES.join(' -> ')}. Teach actively: give one brief instruction or question, then wait without interrupting. Primarily use very simple English. ${hebrewHelp?'A short Hebrew hint is allowed only when confusion is clear.':'Do not use Hebrew.'} Praise genuine effort, correct gently, model pronunciation, ask for a repeat when useful, adapt difficulty conservatively, and give a hint before the answer. Keep every turn short.
Stay within this lesson and approved educational content. Never ask for an address, school name, phone number, password, private detail, or secrecy. Do not discuss sexual, violent, self-harm, illegal, medical, legal, financial, or age-inappropriate topics. Do not contact the child outside this application. If the child describes a personal-safety concern, respond supportively, encourage speaking with a trusted adult, do not investigate or invent facts, and emit a safety flag for the parent.
Pronunciation judgments must be conservative and framed as observations, never objective scores. Use child-friendly Hebrew feedback such as "מצוין", "כמעט", or "בוא ננסה שוב לאט". Never shame, pressure, or compare the child. Do not claim that audio is stored. At phase changes emit a teacher.phase event; for practice observations emit teacher.assessment. End after the required goodbye or when the parent ends the session.`}
module.exports={PHASES,clamp,dateKeys,limits,canStart,safeContext,systemPrompt};
