const PHASES=['greeting','warm-up','teach-vocabulary','listen-repeat','comprehension','speaking','review','summary','goodbye'];
function clamp(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function dateKeys(now=new Date()){const day=now.toISOString().slice(0,10),month=day.slice(0,7);return{day,month}}
function limits(input={}){return{dailyMinutes:clamp(input.dailyMinutes,1,60,5),maxSessionsPerDay:clamp(input.maxSessionsPerDay,1,10,1),monthlyMinutes:clamp(input.monthlyMinutes,1,2000,30),maxSessionCostCents:clamp(input.maxSessionCostCents,1,1000,25),monthlyBudgetCents:clamp(input.monthlyBudgetCents,1,100000,300),idleTimeoutSeconds:clamp(input.idleTimeoutSeconds,15,300,45)}}
function canStart(usage={},requested={}){const l=limits(requested);if((usage.daySessions||0)>=l.maxSessionsPerDay)return{ok:false,error:'daily-session-limit'};if((usage.daySeconds||0)>=l.dailyMinutes*60)return{ok:false,error:'daily-minute-limit'};if((usage.monthSeconds||0)>=l.monthlyMinutes*60)return{ok:false,error:'monthly-minute-limit'};if((usage.monthCostCents||0)>=l.monthlyBudgetCents)return{ok:false,error:'monthly-budget-limit'};if((usage.estimatedSessionCostCents||0)>l.maxSessionCostCents)return{ok:false,error:'session-cost-limit'};const ratio=(usage.monthCostCents||0)/l.monthlyBudgetCents,warning=ratio>=.9?90:ratio>=.75?75:ratio>=.5?50:null;return{ok:true,limits:l,warning}}
function safeValidation(value={}){const list=(name,count=20,size=180)=>(value[name]||[]).slice(0,count).map(x=>String(x).slice(0,size));return{exerciseId:String(value.exerciseId||'').slice(0,100),question:String(value.question||'').slice(0,240),kind:value.kind==='sentence'?'sentence':'single-word',difficulty:['easy','medium','hard'].includes(value.difficulty)?value.difficulty:'medium',expectedAnswers:list('expectedAnswers',12),acceptedSynonyms:list('acceptedSynonyms'),pronunciationVariations:list('pronunciationVariations'),recognitionAlternatives:list('recognitionAlternatives'),rejectedExamples:list('rejectedExamples'),hints:list('hints',8,240),misconceptionExplanations:list('misconceptionExplanations',8,300),followUpPrompts:list('followUpPrompts',8,240),reviewWords:list('reviewWords',20,80),requiredKeywords:list('requiredKeywords',20,60),keywordMode:value.keywordMode==='any'?'any':'all',minimumThreshold:clamp(value.minimumThreshold,.5,1,.8)}}
function safeContext(input={}){const lesson=input.sharedLesson?.lesson||input.lesson||{},child=input.child||{},adaptive=input.sharedLesson?.adaptive||input.adaptive||{},rawSkills=input.sharedLesson?.skillLevels||adaptive.skillLevels||{},skillLevels={};for(const k of ['vocabulary','listening','speaking','pronunciation','sentenceBuilding','reading','comprehension'])skillLevels[k]=clamp(rawSkills[k],1,10,1);return{lesson:{id:String(lesson.id||'').slice(0,80),title:String(lesson.title||'').slice(0,120),titleHe:String(lesson.titleHe||'').slice(0,120),phrases:(lesson.phrases||[]).slice(0,20).map(p=>({english:String(p.english||'').slice(0,180),hebrew:String(p.hebrew||'').slice(0,180),validation:safeValidation(p.validation)})),quiz:(lesson.quiz||[]).slice(0,12).map(q=>({question:String(q.question||'').slice(0,240),expected:String(q.options?.[q.answer]||q.validation?.expectedAnswers?.[0]||'').slice(0,180),validation:safeValidation(q.validation)}))},child:{id:String(child.id||'').slice(0,100),name:String(child.name||'Learner').replace(/[<>]/g,'').slice(0,30),age:clamp(child.age,6,12,null),level:clamp(child.level,1,50,1)},adaptive:{currentDifficulty:clamp(input.sharedLesson?.currentDifficulty||adaptive.currentDifficulty,1,10,1),allowedMaximumLevel:clamp(input.sharedLesson?.allowedMaximumLevel||adaptive.allowedMaximumLevel,1,10,10),skillLevels,recentEvidence:(adaptive.recentEvidence||[]).slice(0,20)},mistakes:(input.mistakes||[]).slice(0,20),completed:(input.completed||[]).slice(0,100),assignment:input.assignment?String(input.assignment).slice(0,300):null}}
function systemPrompt(context,{hebrewHelp=true}={}){const c=safeContext(context),targets=c.lesson.phrases.map(p=>`${p.english} (${p.hebrew}); validation=${JSON.stringify(p.validation)}`).join('; '),answers=c.lesson.quiz.map(q=>`${q.question} => ${q.expected}; validation=${JSON.stringify(q.validation)}`).join('; ');return `You are the Emily voice teacher for one child age 6-12. Child first name: ${c.child.name}. Level: ${c.child.level}. Current lesson only: ${c.lesson.title}. Approved vocabulary and validation: ${targets}. Expected answers and authoritative validation contracts: ${answers}. Previous lesson mistakes: ${JSON.stringify(c.mistakes)}. Completed lesson IDs: ${c.completed.join(', ')}. Current assignment: ${c.assignment||'none'}.
Adaptive skill levels: ${JSON.stringify(c.adaptive.skillLevels)}. Current difficulty: ${c.adaptive.currentDifficulty}/10. Parent maximum: ${c.adaptive.allowedMaximumLevel}/10. Never teach or claim a level above that maximum, and never promote a skill yourself; only the deterministic client evidence engine may change levels.
Follow every phase in order and do not skip learning goals: ${PHASES.join(' -> ')}. Teach actively: give one brief instruction or question, then wait without interrupting. Primarily use very simple English. ${hebrewHelp?'A short Hebrew hint is allowed only when confusion is clear.':'Do not use Hebrew.'} Praise genuine effort, correct gently, model pronunciation, ask for a repeat when useful, adapt difficulty conservatively, and keep every turn short.
Use the shared conversation states teacherSpeaking, waitingForChild, childSpeaking, validating, correcting, praising, paused, and disconnected. Never speak over the child. Keep English and Hebrew in separate turns, use short phrases with natural pauses, and vary praise only when it matches actual performance.
Stay within this lesson and approved educational content. Never ask for an address, school name, phone number, password, private detail, or secrecy. Do not discuss sexual, violent, self-harm, illegal, medical, legal, financial, or age-inappropriate topics. If the child describes a personal-safety concern, respond supportively, encourage speaking with a trusted adult, do not investigate or invent facts, and emit a safety flag for the parent.
Pronunciation judgments must be conservative and framed as observations, never objective scores. Never shame, pressure, or compare the child. Do not claim that audio is stored. At phase changes emit a teacher.phase event; for practice observations emit teacher.assessment. End after the required goodbye or when the parent ends the session.
The frontend deterministic validator is authoritative and classifies every spoken answer as exactly one of: correct, almost-correct, wrong-related, completely-unrelated, didnt-answer, or speech-recognition-uncertain. Never call an answer correct until a DETERMINISTIC VALIDATOR CATEGORY: CORRECT instruction arrives. Follow the supplied response literally. For almost-correct, explain the small mistake and retry. For wrong-related, acknowledge the reasoning, explain the misconception, and retry. For completely-unrelated, say it does not answer the question and bring the child back without advancing. For silence, repeat once and then offer two choices. For uncertain recognition, never blame the child; ask again and offer choices after three uncertain transcripts. Never let random speech skip learning.`}
module.exports={PHASES,clamp,dateKeys,limits,canStart,safeValidation,safeContext,systemPrompt};
const PHASES=['greeting','warm-up','teach-vocabulary','listen-repeat','comprehension','speaking','review','summary','goodbye'];
function clamp(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function dateKeys(now=new Date()){const day=now.toISOString().slice(0,10),month=day.slice(0,7);return{day,month}}
function limits(input={}){return{dailyMinutes:clamp(input.dailyMinutes,1,60,5),maxSessionsPerDay:clamp(input.maxSessionsPerDay,1,10,1),monthlyMinutes:clamp(input.monthlyMinutes,1,2000,30),maxSessionCostCents:clamp(input.maxSessionCostCents,1,1000,25),monthlyBudgetCents:clamp(input.monthlyBudgetCents,1,100000,300),idleTimeoutSeconds:clamp(input.idleTimeoutSeconds,15,300,45)}}
function canStart(usage={},requested={}){const l=limits(requested);if((usage.daySessions||0)>=l.maxSessionsPerDay)return{ok:false,error:'daily-session-limit'};if((usage.daySeconds||0)>=l.dailyMinutes*60)return{ok:false,error:'daily-minute-limit'};if((usage.monthSeconds||0)>=l.monthlyMinutes*60)return{ok:false,error:'monthly-minute-limit'};if((usage.monthCostCents||0)>=l.monthlyBudgetCents)return{ok:false,error:'monthly-budget-limit'};if((usage.estimatedSessionCostCents||0)>l.maxSessionCostCents)return{ok:false,error:'session-cost-limit'};const ratio=(usage.monthCostCents||0)/l.monthlyBudgetCents,warning=ratio>=.9?90:ratio>=.75?75:ratio>=.5?50:null;return{ok:true,limits:l,warning}}
function safeValidation(value={}){const list=(name,count=20,size=180)=>(value[name]||[]).slice(0,count).map(x=>String(x).slice(0,size));return{exerciseId:String(value.exerciseId||'').slice(0,100),question:String(value.question||'').slice(0,240),kind:value.kind==='sentence'?'sentence':'single-word',difficulty:['easy','medium','hard'].includes(value.difficulty)?value.difficulty:'medium',expectedAnswers:list('expectedAnswers',12),acceptedSynonyms:list('acceptedSynonyms'),pronunciationVariations:list('pronunciationVariations'),recognitionAlternatives:list('recognitionAlternatives'),rejectedExamples:list('rejectedExamples'),hints:list('hints',8,240),misconceptionExplanations:list('misconceptionExplanations',8,300),followUpPrompts:list('followUpPrompts',8,240),reviewWords:list('reviewWords',20,80),requiredKeywords:list('requiredKeywords',20,60),keywordMode:value.keywordMode==='any'?'any':'all',minimumThreshold:clamp(value.minimumThreshold,.5,1,.8)}}
function safeContext(input={}){const lesson=input.sharedLesson?.lesson||input.lesson||{},child=input.child||{},adaptive=input.sharedLesson?.adaptive||input.adaptive||{},rawSkills=input.sharedLesson?.skillLevels||adaptive.skillLevels||{},skillLevels={};for(const k of ['vocabulary','listening','speaking','pronunciation','sentenceBuilding','reading','comprehension'])skillLevels[k]=clamp(rawSkills[k],1,10,1);return{lesson:{id:String(lesson.id||'').slice(0,80),title:String(lesson.title||'').slice(0,120),titleHe:String(lesson.titleHe||'').slice(0,120),phrases:(lesson.phrases||[]).slice(0,20).map(p=>({english:String(p.english||'').slice(0,180),hebrew:String(p.hebrew||'').slice(0,180),validation:safeValidation(p.validation)})),quiz:(lesson.quiz||[]).slice(0,12).map(q=>({question:String(q.question||'').slice(0,240),expected:String(q.options?.[q.answer]||q.validation?.expectedAnswers?.[0]||'').slice(0,180),validation:safeValidation(q.validation)}))},child:{id:String(child.id||'').slice(0,100),name:String(child.name||'Learner').replace(/[<>]/g,'').slice(0,30),age:clamp(child.age,6,12,null),level:clamp(child.level,1,50,1)},adaptive:{currentDifficulty:clamp(input.sharedLesson?.currentDifficulty||adaptive.currentDifficulty,1,10,1),allowedMaximumLevel:clamp(input.sharedLesson?.allowedMaximumLevel||adaptive.allowedMaximumLevel,1,10,10),skillLevels,recentEvidence:(adaptive.recentEvidence||[]).slice(0,20)},mistakes:(input.mistakes||[]).slice(0,20),completed:(input.completed||[]).slice(0,100),assignment:input.assignment?String(input.assignment).slice(0,300):null}}
function systemPrompt(context,{hebrewHelp=true}={}){const c=safeContext(context),targets=c.lesson.phrases.map(p=>`${p.english} (${p.hebrew}); validation=${JSON.stringify(p.validation)}`).join('; '),answers=c.lesson.quiz.map(q=>`${q.question} => ${q.expected}; validation=${JSON.stringify(q.validation)}`).join('; ');return `You are the English Adventure voice teacher for one child age 6-12. Child first name: ${c.child.name}. Level: ${c.child.level}. Current lesson only: ${c.lesson.title}. Approved vocabulary and validation: ${targets}. Expected answers and authoritative validation contracts: ${answers}. Previous lesson mistakes: ${JSON.stringify(c.mistakes)}. Completed lesson IDs: ${c.completed.join(', ')}. Current assignment: ${c.assignment||'none'}.
Adaptive skill levels: ${JSON.stringify(c.adaptive.skillLevels)}. Current difficulty: ${c.adaptive.currentDifficulty}/10. Parent maximum: ${c.adaptive.allowedMaximumLevel}/10. Never teach or claim a level above that maximum, and never promote a skill yourself; only the deterministic client evidence engine may change levels.
Follow every phase in order and do not skip learning goals: ${PHASES.join(' -> ')}. Teach actively: give one brief instruction or question, then wait without interrupting. Primarily use very simple English. ${hebrewHelp?'A short Hebrew hint is allowed only when confusion is clear.':'Do not use Hebrew.'} Praise genuine effort, correct gently, model pronunciation, ask for a repeat when useful, adapt difficulty conservatively, and keep every turn short.
Use the shared conversation states teacherSpeaking, waitingForChild, childSpeaking, validating, correcting, praising, paused, and disconnected. Never speak over the child. Keep English and Hebrew in separate turns, use short phrases with natural pauses, and vary praise only when it matches actual performance.
Stay within this lesson and approved educational content. Never ask for an address, school name, phone number, password, private detail, or secrecy. Do not discuss sexual, violent, self-harm, illegal, medical, legal, financial, or age-inappropriate topics. If the child describes a personal-safety concern, respond supportively, encourage speaking with a trusted adult, do not investigate or invent facts, and emit a safety flag for the parent.
Pronunciation judgments must be conservative and framed as observations, never objective scores. Never shame, pressure, or compare the child. Do not claim that audio is stored. At phase changes emit a teacher.phase event; for practice observations emit teacher.assessment. End after the required goodbye or when the parent ends the session.
The frontend deterministic validator is authoritative and classifies every spoken answer as exactly one of: correct, almost-correct, wrong-related, completely-unrelated, didnt-answer, or speech-recognition-uncertain. Never call an answer correct until a DETERMINISTIC VALIDATOR CATEGORY: CORRECT instruction arrives. Follow the supplied response literally. For almost-correct, explain the small mistake and retry. For wrong-related, acknowledge the reasoning, explain the misconception, and retry. For completely-unrelated, say it does not answer the question and bring the child back without advancing. For silence, repeat once and then offer two choices. For uncertain recognition, never blame the child; ask again and offer choices after three uncertain transcripts. Never let random speech skip learning.`}
module.exports={PHASES,clamp,dateKeys,limits,canStart,safeValidation,safeContext,systemPrompt};
