/* English Adventure 2.0 — local-first learning app. No data leaves this device. */
const VERSION='4.2.0', STORE='ea-v2', PIN='ea-parent-pin';
const I18N={he:{install:'התקנה',parents:'להורים',learningNow:'לומדים עכשיו',helloTag:'לומדים • משחקים • מצליחים',welcomeText:'שיעורים קצרים ומשחקיים, תרגול הגייה והישגים שנשמרים רק במכשיר הזה.',level:'רמה',streak:'רצף',badges:'תגים',dailyGoal:'היעד היומי',practiceMistakes:'תרגול טעויות',dailyReview:'החזרה היומית',startReview:'מתחילים חזרה',adventureMap:'מפת ההרפתקה',chooseLesson:'בוחרים נושא ומתחילים לשחק',privacyTitle:'הפרטיות שלכם חשובה',privacyText:'אין כאן פרסומות, מעקב או שליחת מידע. שמות הילדים וההתקדמות נשמרים רק בדפדפן במכשיר הזה.',manageProfiles:'ניהול פרופילים',newName:'שם חדש',addProfile:'הוספת פרופיל',parentArea:'אזור הורים',newVersion:'גרסה חדשה זמינה',update:'עדכון'},en:{install:'Install',parents:'Parents',learningNow:'Learning now',helloTag:'Learn • Play • Succeed',welcomeText:'Short playful lessons, pronunciation practice, and achievements saved only on this device.',level:'Level',streak:'Streak',badges:'Badges',dailyGoal:'Daily goal',practiceMistakes:'Practice mistakes',dailyReview:'Daily review',startReview:'Start review',adventureMap:'Adventure map',chooseLesson:'Choose a topic and start playing',privacyTitle:'Your privacy matters',privacyText:'No ads, tracking, or data sharing. Names and progress stay in this browser on this device.',manageProfiles:'Manage profiles',newName:'New name',addProfile:'Add profile',parentArea:'Parent area',newVersion:'New version available',update:'Update'}};
const CATS={all:['הכול','All'],greetings:['ברכות','Greetings'],family:['משפחה','Family'],colors:['צבעים','Colors'],numbers:['מספרים','Numbers'],food:['אוכל','Food'],home:['בית','Home'],school:['בית ספר','School'],animals:['חיות','Animals'],body:['גוף','Body'],clothing:['בגדים','Clothing'],weather:['מזג אוויר','Weather'],emotions:['רגשות','Emotions'],shopping:['קניות','Shopping'],cafe:['בית קפה','Café'],directions:['כיוונים','Directions'],travel:['נסיעות','Travel']};
const safeParse=(v,f)=>{try{return JSON.parse(v)||f}catch{return f}}, today=()=>new Date().toISOString().slice(0,10);
const blankProgress=()=>({xp:0,completed:[],mistakes:[],activity:[],awards:{},study:{},lastDay:'',streak:0,teacherSessions:[],lessonHistory:[]});
let data=safeParse(localStorage.getItem(STORE),null)||{lang:'he',selected:'p1',profiles:[{id:'p1',name:'ליהי',p:blankProgress()},{id:'p2',name:'אורי',p:blankProgress()},{id:'p3',name:'רפאל',p:blankProgress()}]};
if(!Array.isArray(data.profiles)||!data.profiles.length)data={lang:'he',selected:'p1',profiles:[{id:'p1',name:'ליהי',p:blankProgress()}]};
data.settings={...(data.settings||{})};data.syncMeta={...(data.syncMeta||{})};data.deletedProfiles={...(data.deletedProfiles||{})};
data.profiles.forEach(x=>x.p={...blankProgress(),...(x.p||{})}); let lessons=[],active=null,step=0,score=0,category='all',lastFocus=null,reviewMode=false,deferredInstall=null,waitingSW=null,syncApplying=false;
const $=s=>document.querySelector(s), profile=()=>data.profiles.find(x=>x.id===data.selected)||data.profiles[0];
function save(options={}){localStorage.setItem(STORE,JSON.stringify(data));if(!syncApplying&&!options.localOnly)window.EASync?.markDirty(structuredClone(data))} function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function cleanName(v){return String(v).replace(/[<>"'&]/g,'').replace(/\s+/g,' ').trim().slice(0,20)}
function tr(k){return I18N[data.lang][k]||k} function showToast(t){const n=$('#toast');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2300)}
function openModal(id){lastFocus=document.activeElement;$(id).classList.add('open');document.body.style.overflow='hidden';setTimeout(()=>$(id).querySelector('button,input')?.focus(),0)}
function closeModal(node){node.closest('.modal').classList.remove('open');document.body.style.overflow='';lastFocus?.focus()}
function setLang(lang){data.lang=lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';document.querySelectorAll('[data-i]').forEach(n=>n.textContent=tr(n.dataset.i));$('#langBtn').textContent=lang==='he'?'EN':'עברית';save();renderAll()}
function award(key,amount,label){const p=profile().p,stamp=`${today()}:${key}`;if(p.awards[stamp])return false;p.awards[stamp]=amount;p.xp+=amount;p.study[today()]=(p.study[today()]||0)+1;const d=today();if(p.lastDay!==d){const prev=new Date(Date.now()-864e5).toISOString().slice(0,10);p.streak=p.lastDay===prev?p.streak+1:1;p.lastDay=d}p.activity.unshift({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,at:new Date().toISOString(),label,xp:amount});p.activity=p.activity.slice(0,80);save();renderDashboard();return true}
function renderAll(){renderProfiles();renderDashboard();renderFilters();renderLessons();renderReview()}
function renderProfiles(){const box=$('#profileChips');box.replaceChildren();data.profiles.forEach(x=>{const b=el('button','chip'+(x.id===data.selected?' active':''),x.name);b.onclick=()=>{data.selected=x.id;save();renderAll()};box.append(b)});$('#currentName').textContent=profile().name}
function renderDashboard(){const p=profile().p,level=Math.floor(p.xp/100)+1,badges=[p.completed.length>=1,p.completed.length>=5,p.completed.length>=10,p.streak>=3,p.xp>=500].filter(Boolean).length,dayXP=Object.keys(p.awards).filter(k=>k.startsWith(today())).reduce((a,k)=>a+1,0);$('#xpStat').textContent=p.xp;$('#levelStat').textContent=level;$('#streakStat').textContent=`${p.streak}🔥`;$('#badgeStat').textContent=`${badges}🏅`;$('#goalFill').style.width=`${Math.min(100,dayXP*10)}%`;$('#goalText').textContent=data.lang==='he'?`${Math.min(dayXP,10)} מתוך 10 פעילויות היום`:`${Math.min(dayXP,10)} of 10 activities today`;$('#welcomeTitle').textContent=data.lang==='he'?`${profile().name}, ההרפתקה שלך מתחילה!`:`${profile().name}, your adventure begins!`}
function renderFilters(){const box=$('#filters');box.replaceChildren();Object.keys(CATS).filter(k=>k==='all'||lessons.some(l=>l.category===k)).forEach(k=>{const b=el('button','filter'+(category===k?' active':''),CATS[k][data.lang==='he'?0:1]);b.onclick=()=>{category=k;renderFilters();renderLessons()};box.append(b)})}
function renderLessons(){const box=$('#lessonGrid');box.replaceChildren();lessons.filter(l=>category==='all'||l.category===category).forEach(l=>{const a=el('article','lesson'),icon=el('div','emoji',l.icon),h=el('h3','',data.lang==='he'?l.titleHe:l.title),d=el('p','',data.lang==='he'?l.descriptionHe:l.description),f=document.createElement('footer'),m=el('span',profile().p.completed.includes(l.id)?'done':'',profile().p.completed.includes(l.id)?'✓ '+(data.lang==='he'?'הושלם':'Done'):`${l.phrases.length} ⭐`),b=el('button','primary',data.lang==='he'?'מתחילים':'Start');b.onclick=()=>startLesson(l);f.append(m,b);a.append(icon,h,d,f);box.append(a)})}
function renderReview(){const due=profile().p.mistakes.filter(m=>!m.next||m.next<=Date.now());$('#reviewText').textContent=data.lang==='he'?`${due.length} שאלות מחכות לתרגול. תשובות נכונות מחזקות את הזיכרון.`:`${due.length} questions are ready. Correct answers strengthen memory.`;$('#reviewCardBtn').disabled=!due.length;$('#reviewBtn').disabled=!due.length}
function startLesson(l){active=l;step=0;score=0;reviewMode=false;$('#lessonTitle').textContent=`${l.icon} ${data.lang==='he'?l.titleHe:l.title}`;$('#lessonCat').textContent=CATS[l.category][data.lang==='he'?0:1];openModal('#lessonModal');renderStep()}
function renderStep(){const body=$('#lessonBody');body.replaceChildren();const pc=active.phrases.length,qc=active.quiz.length,total=pc+qc+2;$('#stepFill').style.width=`${Math.round(step/total*100)}%`;if(step<pc)return renderPhrase(body,active.phrases[step]);if(step<pc+qc)return renderQuiz(body,active.quiz[step-pc]);if(step===pc+qc)return renderOrder(body);if(step===pc+qc+1)return renderSummary(body);finishLesson(body)}
function heading(body,title,sub){body.append(el('h3','',title),el('p','muted',sub))} function nextButton(body,label=data.lang==='he'?'הבא':'Next'){const b=el('button','primary',label);b.onclick=()=>{step++;renderStep()};body.append(b)}
function renderPhrase(body,p){heading(body,data.lang==='he'?'מקשיבים וחוזרים':'Listen and repeat',data.lang==='he'?'לחצו על הרמקול ואז אמרו את המשפט בקול.':'Tap the speaker, then say the phrase aloud.');const card=el('div','phrase'),en=el('div','english',p.english),he=el('p','muted',p.hebrew),acts=el('div','phrase-actions'),s=el('button','round','🔊 '+(data.lang==='he'?'שמיעה':'Listen')),mic=el('button','round','🎤 '+(data.lang==='he'?'הקלטה':'Repeat')),fb=el('div','feedback','');s.setAttribute('aria-label','Hear English phrase');mic.setAttribute('aria-label','Practice pronunciation');s.onclick=()=>{speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(p.english);u.lang='en-US';u.rate=.82;speechSynthesis?.speak(u);if(award(`speak:${active.id}:${step}`,2,'Pronunciation practice'))showToast('+2 XP')};mic.onclick=()=>recognize(p.english,fb);acts.append(s,mic);card.append(en,he,acts,fb);body.append(card);const done=el('button','primary',data.lang==='he'?'סיימתי את המשפט +5 XP':'Phrase complete +5 XP');done.onclick=()=>{if(award(`phrase:${active.id}:${step}`,5,'Phrase completed'))showToast('+5 XP');step++;renderStep()};body.append(done)}
function normalize(s){return s.toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim()} function similarity(a,b){a=normalize(a);b=normalize(b);const A=new Set(a.split(' ')),B=new Set(b.split(' '));return Math.round(100*[...A].filter(x=>B.has(x)).length/Math.max(A.size,B.size,1))}
function recognize(expected,fb){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){fb.textContent=data.lang==='he'?'הדפדפן הזה לא תומך בזיהוי דיבור. אפשר עדיין להקשיב ולחזור בקול.':'Speech recognition is unavailable here. You can still listen and repeat.';return}const r=new SR();r.lang='en-US';r.interimResults=false;fb.textContent=data.lang==='he'?'מקשיבים…':'Listening…';r.onresult=e=>{const heard=e.results[0][0].transcript,s=similarity(heard,expected);fb.textContent=(data.lang==='he'?`שמענו: “${heard}” — התאמה ${s}%`:`We heard “${heard}” — ${s}% match`)+(s>=75?' 🌟':' 💪');if(s>=75&&award(`mic:${active.id}:${step}`,5,'Pronunciation success'))showToast('+5 XP')};r.onerror=()=>fb.textContent=data.lang==='he'?'לא הצלחנו לשמוע. בדקו הרשאת מיקרופון ונסו שוב.':'We could not hear you. Check microphone permission and try again.';r.start()}
function renderQuiz(body,q){heading(body,data.lang==='he'?'שאלה קצרה':'Quick question',data.lang==='he'?q.questionHe:q.question);const fb=el('div','feedback','');q.options.forEach((o,i)=>{const b=el('button','option',data.lang==='he'?(q.optionsHe?.[i]||o):o);b.onclick=()=>{body.querySelectorAll('.option').forEach(x=>x.disabled=true);body.querySelectorAll('.option')[q.answer].classList.add('correct');if(i===q.answer){b.classList.add('correct');score++;fb.textContent=data.lang==='he'?'מצוין! תשובה נכונה 🌟':'Excellent! Correct 🌟';award(`quiz:${active.id}:${step}`,10,'Correct answer');resolveMistake(active.id,q.id)}else{b.classList.add('wrong');fb.textContent=data.lang==='he'?'כמעט! ננסה שוב בחזרה היומית.':'Almost! We will try again in daily review.';addMistake(active,q)}nextButton(body)};body.append(b)});body.append(fb)}
function addMistake(l,q){const p=profile().p,m=p.mistakes.find(x=>x.lesson===l.id&&x.qid===q.id);if(m){m.next=Date.now()+864e5;m.tries=0}else p.mistakes.push({lesson:l.id,qid:q.id,next:Date.now()+36e5,tries:0});save();renderReview()}function resolveMistake(lid,qid){const m=profile().p.mistakes.find(x=>x.lesson===lid&&x.qid===qid);if(!m)return;m.tries=(m.tries||0)+1;if(m.tries>=3)profile().p.mistakes=profile().p.mistakes.filter(x=>x!==m);else m.next=Date.now()+864e5*Math.pow(2,m.tries);save()}
function renderOrder(body){heading(body,data.lang==='he'?'מסדרים משפט':'Put the sentence in order',data.lang==='he'?'איזה סדר יוצר משפט נכון?':'Which order makes a correct sentence?');const phrase=active.phrases[0].english,words=phrase.replace(/[?.!]/g,'').split(' '),shuffled=[...words].reverse(),out=el('div','phrase english',''),pool=el('div','phrase-actions');shuffled.forEach(w=>{const b=el('button','round',w);b.onclick=()=>{out.textContent+=(out.textContent?' ':'')+w;b.disabled=true};pool.append(b)});const check=el('button','primary',data.lang==='he'?'בדיקה':'Check');check.onclick=()=>{if(normalize(out.textContent)===normalize(words.join(' '))){showToast(data.lang==='he'?'סדר מצוין! +8 XP':'Great order! +8 XP');award(`order:${active.id}`,8,'Ordering activity');step++;renderStep()}else{out.textContent='';pool.querySelectorAll('button').forEach(b=>b.disabled=false);showToast(data.lang==='he'?'נסו שוב':'Try again')}};body.append(out,pool,check)}
function renderSummary(body){heading(body,data.lang==='he'?'חזרה מהירה':'Quick review',data.lang==='he'?`למדנו ${active.phrases.length} משפטים. לחצו לשמוע שוב לפני הסיום.`:`We learned ${active.phrases.length} phrases. Listen once more before finishing.`);active.phrases.forEach(p=>{const b=el('button','option',`🔊 ${p.english} — ${p.hebrew}`);b.onclick=()=>{const u=new SpeechSynthesisUtterance(p.english);u.lang='en-US';speechSynthesis.speak(u)};body.append(b)});nextButton(body,data.lang==='he'?'סיום השיעור':'Finish lesson')}
function finishLesson(body){const p=profile().p;if(!p.completed.includes(active.id))p.completed.push(active.id);award(`finish:${active.id}`,30,'Lesson completed');save();renderAll();const c=el('div','celebrate');c.append(el('div','confetti','★ ✦ ★ ✦'),el('div','trophy','🏆'),el('h2','',data.lang==='he'?'כל הכבוד! השיעור הושלם':'Great job! Lesson complete'),el('p','',`${score}/${active.quiz.length} • +30 XP`));const b=el('button','primary',data.lang==='he'?'חזרה למפה':'Back to map');b.onclick=()=>closeModal($('#lessonModal'));c.append(b);body.append(c)}
function startReview(){const m=profile().p.mistakes.find(x=>!x.next||x.next<=Date.now());if(!m)return showToast(data.lang==='he'?'אין טעויות לתרגול כרגע':'No mistakes are due');const l=lessons.find(x=>x.id===m.lesson),q=l?.quiz.find(x=>x.id===m.qid);if(!l||!q)return;active={...l,phrases:[],quiz:[q]};step=0;score=0;$('#lessonTitle').textContent=data.lang==='he'?'תרגול טעויות':'Practice mistakes';$('#lessonCat').textContent='🔁';openModal('#lessonModal');renderStep()}
function manageProfiles(){const box=$('#profilesList');box.replaceChildren();data.profiles.forEach(x=>{const row=el('div','row'),name=el('strong','',x.name),edit=el('button','btn','✏️'),del=el('button','btn','🗑️');edit.onclick=()=>{const n=cleanName(prompt(data.lang==='he'?'שם חדש':'New name',x.name));if(n){x.name=n;x.updatedAt=Date.now();save();manageProfiles();renderAll()}};del.onclick=()=>{if(data.profiles.length===1)return showToast(data.lang==='he'?'צריך לפחות פרופיל אחד':'Keep at least one profile');if(confirm(data.lang==='he'?`למחוק את ${x.name}? הנתונים יישמרו בגיבוי הענן לפני הסנכרון.`:`Delete ${x.name}? Cloud backups remain available.`)){data.deletedProfiles[x.id]=Date.now();data.profiles=data.profiles.filter(p=>p!==x);if(data.selected===x.id)data.selected=data.profiles[0].id;save();manageProfiles();renderAll()}};row.append(name,edit,del);box.append(row)});openModal('#profilesModal')}
async function hashPin(value){const bytes=new TextEncoder().encode(`english-adventure:${value}`),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function requestParentPin(create=false){return new Promise(resolve=>{let m=$('#parentPinModal');if(!m){m=document.createElement('div');m.className='modal';m.id='parentPinModal';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.setAttribute('aria-labelledby','parentPinTitle');m.innerHTML='<article class="panel"><div class="panelhead"><h2 id="parentPinTitle"></h2><button class="close" type="button" aria-label="ביטול">×</button></div><form class="forms"><label class="field"><span id="parentPinHelp"></span><input id="parentPinInput" inputmode="numeric" autocomplete="off" maxlength="4" pattern="[0-9]{4}" aria-describedby="parentPinHelp" required></label><div class="phrase-actions"><button class="primary" type="submit">אישור</button><button class="btn" type="button" data-cancel>ביטול</button></div></form></article>';document.body.append(m)}const title=$('#parentPinTitle'),help=$('#parentPinHelp'),input=$('#parentPinInput'),form=m.querySelector('form'),finish=value=>{m.classList.remove('open');document.body.style.overflow='';resolve(value)};title.textContent=data.lang==='he'?(create?'יצירת קוד הורים':'קוד הורים'):(create?'Create parent PIN':'Parent PIN');help.textContent=data.lang==='he'?(create?'בחרו 4 ספרות. זו נעילה מקומית נוחה בלבד.':'הקלידו קוד בן 4 ספרות.'):(create?'Choose four digits. This is a local convenience lock.':'Enter the four-digit PIN.');input.value='';m.querySelector('.close').onclick=()=>finish(null);m.querySelector('[data-cancel]').onclick=()=>finish(null);form.onsubmit=e=>{e.preventDefault();finish(/^\d{4}$/.test(input.value)?input.value:'')};m.classList.add('open');document.body.style.overflow='hidden';setTimeout(()=>input.focus(),0)})}
async function parentEntry(){const legacy=localStorage.getItem(PIN);if(legacy&&!data.settings.parentPinHash){data.settings.parentPinHash=await hashPin(legacy);localStorage.removeItem(PIN);save()}if(!data.settings.parentPinHash){const a=await requestParentPin(true);if(a===null)return;if(!/^\d{4}$/.test(a||''))return showToast(data.lang==='he'?'נדרש קוד בן 4 ספרות':'Enter four digits');data.settings.parentPinHash=await hashPin(a);save()}else{const a=await requestParentPin(false);if(a===null)return;if(await hashPin(a||'')!==data.settings.parentPinHash)return showToast(data.lang==='he'?'קוד שגוי':'Incorrect PIN')}renderParent();openModal('#parentModal')}
function renderParent(){const body=$('#parentBody');body.replaceChildren();body.append(el('div','notice',data.lang==='he'?`גרסה ${VERSION}. הקוד הוא נעילה מקומית נוחה בלבד ואינו אבטחה אמיתית. בענן נשמר רק גיבוב של הקוד.`:`Version ${VERSION}. The PIN is a convenience lock only; only its hash is synchronized.`));const grid=el('div','parentgrid');data.profiles.forEach(x=>{const c=el('div','parentcard'),h=el('h3','',x.name),p=x.p;c.append(h,el('p','',`XP: ${p.xp} • ${data.lang==='he'?'שיעורים':'Lessons'}: ${p.completed.length}/${lessons.length}`),el('p','',`${data.lang==='he'?'רצף':'Streak'}: ${p.streak} • ${data.lang==='he'?'טעויות':'Mistakes'}: ${p.mistakes.length}`),el('p','',`${data.lang==='he'?'זמן היום':'Today'}: ${p.study[today()]||0} min`));const reset=el('button','btn',data.lang==='he'?'איפוס התקדמות':'Reset progress');reset.onclick=()=>{if(confirm(data.lang==='he'?`לאפס את ${x.name}?`:`Reset ${x.name}?`)){x.p=blankProgress();save();renderParent();renderAll()}};c.append(reset);grid.append(c)});body.append(grid);const act=el('h3','',data.lang==='he'?'פעילות אחרונה':'Recent activity');body.append(act);const activities=data.profiles.flatMap(x=>x.p.activity.slice(0,5).map(a=>({...a,name:x.name}))).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,10);activities.forEach(a=>body.append(el('div','row',`${a.name}: ${a.label} (+${a.xp} XP)`)));const controls=el('div','phrase-actions'),exp=el('button','primary',data.lang==='he'?'ייצוא JSON':'Export JSON'),imp=el('button','btn',data.lang==='he'?'ייבוא JSON':'Import JSON'),pin=el('button','btn',data.lang==='he'?'שינוי קוד':'Change PIN'),privacy=el('button','btn',data.lang==='he'?'פרטיות בענן':'Cloud privacy');exp.onclick=exportData;imp.onclick=importData;pin.onclick=()=>{delete data.settings.parentPinHash;save();showToast(data.lang==='he'?'הקוד אופס':'PIN cleared')};privacy.onclick=()=>openModal('#cloudPrivacyModal');controls.append(exp,imp,pin,privacy);body.append(controls)}
function exportData(){const blob=new Blob([JSON.stringify({version:VERSION,exported:new Date().toISOString(),data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-adventure-progress.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const parsed=JSON.parse(await input.files[0].text());if(!parsed.data?.profiles?.length)throw 0;data=parsed.data;save();renderAll();renderParent();showToast(data.lang==='he'?'הייבוא הושלם':'Import complete')}catch{showToast(data.lang==='he'?'קובץ לא תקין':'Invalid file')}};input.click()}
document.addEventListener('click',e=>{if(e.target.matches('[data-close]'))closeModal(e.target)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const m=document.querySelector('.modal.open');if(m)closeModal(m)}if(e.key==='Tab'){const m=document.querySelector('.modal.open');if(!m)return;const f=[...m.querySelectorAll('button,input,select')].filter(x=>!x.disabled);if(!f.length)return;if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}}});
$('#langBtn').onclick=()=>setLang(data.lang==='he'?'en':'he');$('#manageProfiles').onclick=manageProfiles;$('#parentBtn').onclick=parentEntry;$('#reviewBtn').onclick=startReview;$('#reviewCardBtn').onclick=startReview;$('#addProfileForm').onsubmit=e=>{e.preventDefault();const n=cleanName($('#newProfileName').value);if(!n)return;const id=crypto.randomUUID?.()||`p-${Date.now()}`;data.profiles.push({id,name:n,updatedAt:Date.now(),p:blankProgress()});data.selected=id;$('#newProfileName').value='';save();manageProfiles();renderAll()};
$('#accountBtn').onclick=()=>{window.EASync?.renderAccount();openModal('#accountModal')};$('#syncStatus').onclick=()=>{window.EASync?.renderAccount();openModal('#accountModal')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true}};
if(navigator.serviceWorker){navigator.serviceWorker.register('sw.js').then(reg=>{const notifyWaiting=()=>{if(reg.waiting&&navigator.serviceWorker.controller){waitingSW=reg.waiting;$('#updateNotice')?.classList.add('show')}};notifyWaiting();reg.addEventListener('updatefound',()=>{const w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller){waitingSW=w;$('#updateNotice')?.classList.add('show')}})})}).catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}const updateBtn=$('#updateBtn');if(updateBtn)updateBtn.onclick=()=>waitingSW?.postMessage({type:'SKIP_WAITING'});
window.EAApp={version:VERSION,getData:()=>structuredClone(data),getLessonContext(){if(!active)return null;const p=profile(),level=Math.floor(p.p.xp/100)+1;return{lesson:structuredClone(active),child:{id:p.id,name:p.name,level,age:data.settings?.childAges?.[p.id]||null},mistakes:structuredClone(p.p.mistakes.filter(m=>m.lesson===active.id)),completed:[...p.p.completed],assignment:data.settings?.currentAssignment||null}},updateTeacherSettings(patch){data.settings.teacherAI={...(data.settings.teacherAI||{}),...patch};save();return structuredClone(data.settings.teacherAI)},recordTeacherSession(summary){const p=profile().p,mode=summary.teacherMode==='advanced'?'advanced':'free';p.teacherSessions=[{...summary,teacherMode:mode,id:summary.id||crypto.randomUUID?.()||`teacher-${Date.now()}`},...(p.teacherSessions||[])].slice(0,40);p.lessonHistory=[{id:summary.id,lessonId:summary.lessonId,type:`${mode}-voice`,teacherMode:mode,completedAt:summary.endedAt||new Date().toISOString(),durationSeconds:summary.durationSeconds||0},...(p.lessonHistory||[])].slice(0,100);p.activity.unshift({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,at:new Date().toISOString(),label:mode==='advanced'?'Advanced AI teacher lesson':'Free guided teacher lesson',xp:0});save();renderAll()},applySyncedData(next){if(!next?.profiles?.length)return false;syncApplying=true;data=structuredClone(next);data.settings={...(data.settings||{})};data.syncMeta={...(data.syncMeta||{})};data.deletedProfiles={...(data.deletedProfiles||{})};data.profiles.forEach(x=>x.p={...blankProgress(),...(x.p||{})});localStorage.setItem(STORE,JSON.stringify(data));syncApplying=false;renderAll();return true},exportData,openParentArea:parentEntry,openModal,closeModal,showToast,renderAll};window.dispatchEvent(new CustomEvent('ea-app-ready'));
fetch('content.json').then(r=>{if(!r.ok)throw 0;return r.json()}).then(j=>{lessons=j.lessons;setLang(data.lang||'he')}).catch(()=>showToast('לא ניתן לטעון את השיעורים / Could not load lessons'));
