/* Parent-provided welcome video, presented before the learning home screen. */
(()=>{
  const seenKey='ea-entry-video-seen';
  const src='assets/entry-welcome.mp4?v=4.42.6';
  const style=document.createElement('style');
  style.textContent=`.ea-video-entry{position:fixed;inset:0;z-index:10020;display:grid;place-items:center;padding:clamp(16px,4vw,42px);overflow:auto;background:radial-gradient(circle at 15% 8%,#9ee8df 0,transparent 35%),radial-gradient(circle at 85% 7%,#b5adff 0,transparent 33%),linear-gradient(145deg,#17203b,#344779);color:#fff;direction:rtl}.ea-video-entry-card{width:min(970px,100%);display:grid;grid-template-columns:minmax(280px,1.08fr) minmax(270px,.92fr);gap:clamp(20px,4vw,48px);align-items:center;padding:clamp(20px,4vw,46px);border:1px solid #ffffff55;border-radius:32px;background:#ffffff14;box-shadow:0 28px 85px #060a1a8a;backdrop-filter:blur(14px)}.ea-video-entry-copy{display:grid;gap:15px}.ea-video-entry-kicker{display:inline-flex;justify-self:start;border-radius:999px;padding:7px 12px;background:#ffffff1d;color:#fff6bd;font-weight:900}.ea-video-entry h1{margin:0;font-size:clamp(2.1rem,5vw,4.2rem);line-height:1.03}.ea-video-entry p{margin:0;color:#f0f3ff;font-size:clamp(1rem,2vw,1.2rem);line-height:1.6}.ea-video-entry-actions{display:flex;gap:10px;flex-wrap:wrap}.ea-video-entry button{border:0;min-height:52px;border-radius:16px;padding:12px 18px;font:inherit;font-weight:900;cursor:pointer}.ea-video-entry-start{background:#ffcf51;color:#17203b;box-shadow:0 10px 24px #ffcf5144}.ea-video-entry-enter{background:#fff;color:#263452}.ea-video-entry-sound{background:#ffffff17;color:#fff;border:1px solid #ffffff4f!important}.ea-video-entry-media{position:relative;overflow:hidden;min-height:310px;border-radius:24px;background:#111a33;box-shadow:0 15px 35px #0c102755}.ea-video-entry video{width:100%;height:100%;min-height:310px;object-fit:cover;display:block}.ea-video-entry-caption{position:absolute;inset:auto 12px 12px 12px;padding:9px 12px;border-radius:13px;background:#111a33be;color:#fff;font-weight:800;backdrop-filter:blur(6px)}.ea-video-entry-close{position:absolute;top:14px;inset-inline-end:14px;width:42px!important;min-height:42px!important;padding:0!important;border-radius:50%!important;background:#ffffff2e!important;color:#fff!important;font-size:1.4rem!important}.ea-video-entry button:focus-visible{outline:3px solid #fff;outline-offset:3px}@media(max-width:720px){.ea-video-entry{place-items:start center;padding:14px}.ea-video-entry-card{grid-template-columns:1fr;padding:18px;border-radius:25px}.ea-video-entry-media{order:-1;min-height:210px}.ea-video-entry video{min-height:210px}.ea-video-entry h1{font-size:clamp(2rem,10vw,3rem)}}@media(prefers-reduced-motion:reduce){.ea-video-entry video{display:none}.ea-video-entry-media{min-height:120px}.ea-video-entry-media:before{content:'English Adventure';display:grid;place-items:center;height:120px;font-weight:900;font-size:1.6rem}}`;
  document.head.append(style);
  const show=()=>{
    const page=document.createElement('section');
    page.className='ea-video-entry';page.setAttribute('role','dialog');page.setAttribute('aria-modal','true');page.setAttribute('aria-labelledby','eaEntryTitle');
    page.innerHTML=`<div class="ea-video-entry-card"><button class="ea-video-entry-close" type="button" aria-label="סגירת חלון">×</button><div class="ea-video-entry-copy"><span class="ea-video-entry-kicker">✨ ברוכים הבאים להרפתקה</span><h1 id="eaEntryTitle">מוכנים לגלות אנגלית בדרך חדשה?</h1><p>המורה מחכה להתחיל איתך הרפתקה קצרה, משחקית ומותאמת במיוחד לך.</p><div class="ea-video-entry-actions"><button class="ea-video-entry-start" type="button">🎙️ התחלת השיעור היומי</button><button class="ea-video-entry-enter" type="button">כניסה לאתר</button><button class="ea-video-entry-sound" type="button" aria-pressed="false">🔊 הפעלת קול</button></div></div><div class="ea-video-entry-media"><video muted autoplay loop playsinline preload="metadata" aria-label="סרטון פתיחה"><source src="${src}" type="video/mp4"></video><div class="ea-video-entry-caption">המורה מחכה לך כאן</div></div></div>`;
    const video=page.querySelector('video');
    const close=()=>{sessionStorage.setItem(seenKey,'1');page.remove();document.querySelector('.daily-start,#dailyLessonBtn')?.focus?.();};
    page.querySelector('.ea-video-entry-close').addEventListener('click',close);
    page.querySelector('.ea-video-entry-enter').addEventListener('click',close);
    page.querySelector('.ea-video-entry-start').addEventListener('click',()=>{close();setTimeout(()=>document.querySelector('.daily-start,#dailyLessonBtn')?.click(),0);});
    const sound=page.querySelector('.ea-video-entry-sound');
    sound.addEventListener('click',()=>{video.muted=!video.muted;sound.setAttribute('aria-pressed',String(!video.muted));sound.textContent=video.muted?'🔊 הפעלת קול':'🔇 השתקת קול';video.play().catch(()=>{});});
    document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.contains(page))close();},{once:true});
    document.body.append(page);
    video.load();
    video.play().catch(()=>{});
    page.querySelector('.ea-video-entry-start').focus();
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',show,{once:true});else show();
})();
