import { firebaseConfig } from './firebase-config.js';

const DEVICE_KEY='ea-device-id', PENDING_KEY='ea-sync-pending', LAST_KEY='ea-last-sync';
const deviceId=localStorage.getItem(DEVICE_KEY)||crypto.randomUUID();localStorage.setItem(DEVICE_KEY,deviceId);
let auth=null,db=null,user=null,api=null,unsubscribe=null,initialized=false,pending=false,pendingMigration=null,syncTimer=null,lastError='';
const appReady=window.EAApp?Promise.resolve():new Promise(resolve=>window.addEventListener('ea-app-ready',resolve,{once:true}));
const $=s=>document.querySelector(s), clone=v=>structuredClone(v), nowIso=()=>new Date().toISOString();

function setStatus(state,text){const pill=$('#syncStatus'),label=$('#syncStatusText');if(!pill||!label)return;pill.dataset.state=state;label.textContent=text;pill.setAttribute('aria-label',text)}
function statusFor(state){return {synced:'מסונכרן',syncing:'מסנכרן…',offline:'עובד במצב לא מקוון',pending:'יש שינויים הממתינים לסנכרון',error:'שגיאת סנכרון'}[state]}
function setPending(value){pending=value;localStorage.setItem(PENDING_KEY,value?'1':'0');if(value)setStatus(navigator.onLine?'pending':'offline',navigator.onLine?statusFor('pending'):statusFor('offline'))}
function meaningful(d){return !!d?.profiles?.some(x=>x.p?.xp||x.p?.completed?.length||x.p?.activity?.length||x.p?.mistakes?.length||x.p?.teacherSessions?.length||x.p?.voiceReview?.length||x.p?.adaptive?.placement?.status!=='not-started'||Object.values(x.p?.adaptive?.skills||{}).some(s=>s?.evidence?.length))||!!d?.settings?.parentPinHash}
function cleanString(v,max=120){return String(v??'').replace(/[<>]/g,'').slice(0,max)}
function activityId(a){return a.id||`${a.at||''}|${a.label||''}|${Number(a.xp)||0}`}
function normalize(raw){
  const d=raw&&typeof raw==='object'?clone(raw):{};
  d.lang=d.lang==='en'?'en':'he';
  d.settings=d.settings&&typeof d.settings==='object'?d.settings:{};
  d.syncMeta=d.syncMeta&&typeof d.syncMeta==='object'?d.syncMeta:{};
  d.deletedProfiles=d.deletedProfiles&&typeof d.deletedProfiles==='object'?d.deletedProfiles:{};
  const sourceProfiles=Array.isArray(d.profiles)?d.profiles:[];
  d.profiles=sourceProfiles.slice(0,20).filter(x=>x&&typeof x.id==='string').map(x=>{
    const p=x.p&&typeof x.p==='object'?x.p:{};
    const activity=Array.isArray(p.activity)?p.activity.slice(0,200).map(a=>({
      id:activityId(a),at:cleanString(a.at,40),label:cleanString(a.label),
      xp:Math.max(0,Math.min(1000,Number(a.xp)||0))
    })):[];
    return {
      id:cleanString(x.id,80),name:cleanString(x.name,20)||'ילד/ה',
      gender:['boy','girl'].includes(x.gender)?x.gender:'not-specified',
      teacherId:['noa','daniel'].includes(x.teacherId)?x.teacherId:null,
      updatedAt:Number(x.updatedAt)||0,
      p:{
        xp:Math.max(0,Number(p.xp)||0),
        completed:[...new Set(Array.isArray(p.completed)?p.completed.map(v=>cleanString(v,80)):[])],
        mistakes:Array.isArray(p.mistakes)?p.mistakes.slice(0,300):[],
        voiceReview:Array.isArray(p.voiceReview)?p.voiceReview.slice(0,100):[],
        teacherSessions:Array.isArray(p.teacherSessions)?p.teacherSessions.slice(0,40):[],
        lessonHistory:Array.isArray(p.lessonHistory)?p.lessonHistory.slice(0,100):[],
        teacherAnalytics:p.teacherAnalytics&&typeof p.teacherAnalytics==='object'?p.teacherAnalytics:{categories:{},words:{},totalAnswers:0,totalRetries:0,recognitionFailures:0,skippedQuestions:0},adaptive:p.adaptive&&typeof p.adaptive==='object'?p.adaptive:null,activity,
        awards:p.awards&&typeof p.awards==='object'?p.awards:{},
        study:p.study&&typeof p.study==='object'?p.study:{},
        lastDay:cleanString(p.lastDay,20),streak:Math.max(0,Number(p.streak)||0)
      }
    };
  });
  if(!d.profiles.length)d.profiles=[{id:crypto.randomUUID(),name:'ילד/ה',gender:'not-specified',updatedAt:Date.now(),p:{xp:0,completed:[],mistakes:[],activity:[],awards:{},study:{},lastDay:'',streak:0}}];
  if(!d.profiles.some(x=>x.id===d.selected))d.selected=d.profiles[0].id;
  return d;
}
function mergeMaps(a={},b={},chooser=(x,y)=>y??x){const out={...a};for(const [k,v]of Object.entries(b))out[k]=k in out?chooser(out[k],v):v;return out}
function mergeById(a=[],b=[],limit=100,key=x=>x.id){const map=new Map();for(const x of [...a,...b]){const id=key(x);if(id)map.set(id,{...(map.get(id)||{}),...x})}return[...map.values()].sort((x,y)=>String(y.endedAt||y.completedAt||y.at||'').localeCompare(String(x.endedAt||x.completedAt||x.at||''))).slice(0,limit)}
function analyticsFromSessions(sessions=[]){const out={categories:{},words:{},totalAnswers:0,totalRetries:0,recognitionFailures:0,skippedQuestions:0};for(const s of sessions){const stats=s.answerAnalytics||{};out.totalAnswers+=Number(stats.totalAnswers)||0;out.totalRetries+=Number(s.retries)||0;out.recognitionFailures+=Number(stats.recognitionFailures)||0;out.skippedQuestions+=Number(stats.skippedQuestions)||0;for(const [k,v]of Object.entries(stats))if(typeof v==='number'&&!['totalAnswers','averageRetries','recognitionFailures','skippedQuestions'].includes(k))out.categories[k]=(out.categories[k]||0)+v;for(const word of s.wordsPracticed||[]){const k=String(word).toLowerCase(),w=out.words[k]||{correct:0,mistakes:0,retries:0};w.correct++;out.words[k]=w}for(const e of s.mistakeEvents||[]){const k=String(e.word||'').toLowerCase(),w=out.words[k]||{correct:0,mistakes:0,retries:0};w.mistakes++;w.retries++;out.words[k]=w}}return out}
function mergeAdaptive(a,b){if(!a)return b||null;if(!b)return a;const newer=(Number(a.updatedAt)||0)>=(Number(b.updatedAt)||0)?a:b,out=clone(newer),skills={};for(const key of new Set([...Object.keys(a.skills||{}),...Object.keys(b.skills||{})])){const x=a.skills?.[key]||{},y=b.skills?.[key]||{},history=mergeById(x.history,y.history,100,z=>z.id||`${z.at}|${z.from}|${z.to}`),evidence=mergeById(x.evidence,y.evidence,240),chosen=(Number(a.updatedAt)||0)>=(Number(b.updatedAt)||0)?x:y;skills[key]={...chosen,evidence,history,confidence:Math.max(Number(x.confidence)||0,Number(y.confidence)||0),level:Math.max(1,Math.min(10,Number(chosen.level)||1))}}out.skills=skills;out.manualLog=mergeById(a.manualLog,b.manualLog,100,z=>z.id||`${z.at}|${z.skill}|${z.to}`);out.pendingReview=mergeById(a.pendingReview,b.pendingReview,100,z=>z.id||`${z.skill}|${z.dueAt}`);out.updatedAt=Math.max(Number(a.updatedAt)||0,Number(b.updatedAt)||0);const levels=Object.values(skills).map(s=>Number(s.level)||1);out.overallLevel=levels.length?Math.round(levels.reduce((n,v)=>n+v,0)/levels.length):1;out.currentDifficulty=Math.min(Number(out.controls?.maxLevel)||10,Math.max(1,out.overallLevel));return out}
function mergeProgress(a={},b={}){const awards=mergeMaps(a.awards,b.awards,(x,y)=>Math.max(Number(x)||0,Number(y)||0));const awardPoints=o=>Object.values(o).reduce((s,v)=>s+(Number(v)>1?Number(v):0),0),base=Math.max(0,(Number(a.xp)||0)-awardPoints(a.awards||{}),(Number(b.xp)||0)-awardPoints(b.awards||{}));const activities=new Map();[...(a.activity||[]),...(b.activity||[])].forEach(x=>activities.set(activityId(x),{...x,id:activityId(x)}));const mistakes=new Map();[...(a.mistakes||[]),...(b.mistakes||[])].forEach(m=>{const k=`${m.lesson}|${m.qid}`,old=mistakes.get(k);mistakes.set(k,old?{...old,...m,tries:Math.max(old.tries||0,m.tries||0),next:Math.min(old.next||Infinity,m.next||Infinity)}:m)});const teacherSessions=mergeById(a.teacherSessions,b.teacherSessions,40),lessonHistory=mergeById(a.lessonHistory,b.lessonHistory,100),voiceReview=mergeById(a.voiceReview,b.voiceReview,100,x=>`${x.lessonId}|${x.exerciseId}|${x.word}`).map(x=>({...x,count:Math.max(Number(x.count)||1,1)}));return{xp:base+awardPoints(awards),completed:[...new Set([...(a.completed||[]),...(b.completed||[])])],mistakes:[...mistakes.values()],voiceReview,teacherSessions,lessonHistory,teacherAnalytics:analyticsFromSessions(teacherSessions),adaptive:mergeAdaptive(a.adaptive,b.adaptive),activity:[...activities.values()].sort((x,y)=>String(y.at).localeCompare(String(x.at))).slice(0,200),awards,study:mergeMaps(a.study,b.study,(x,y)=>Math.max(Number(x)||0,Number(y)||0)),lastDay:String(a.lastDay||'')>String(b.lastDay||'')?a.lastDay:b.lastDay,streak:Math.max(a.streak||0,b.streak||0)} }
export function mergeStates(localRaw,cloudRaw){const local=normalize(localRaw),cloud=normalize(cloudRaw),deleted=mergeMaps(local.deletedProfiles,cloud.deletedProfiles,(x,y)=>Math.max(Number(x)||0,Number(y)||0)),map=new Map();for(const x of [...cloud.profiles,...local.profiles]){const tomb=Number(deleted[x.id])||0;if(tomb>=(Number(x.updatedAt)||0)){map.delete(x.id);continue}const old=map.get(x.id);if(!old)map.set(x.id,clone(x));else{const newer=(x.updatedAt||0)>=(old.updatedAt||0)?x:old;map.set(x.id,{id:x.id,name:newer.name,gender:newer.gender||'not-specified',teacherId:newer.teacherId||null,updatedAt:Math.max(x.updatedAt||0,old.updatedAt||0),p:mergeProgress(old.p,x.p)})}}const profiles=[...map.values()];return normalize({...cloud,...local,profiles,deletedProfiles:deleted,settings:{...cloud.settings,...local.settings},syncMeta:{...cloud.syncMeta,...local.syncMeta}})}
function same(a,b){const strip=d=>{const c=clone(d);delete c.syncMeta;return JSON.stringify(c)};return strip(normalize(a))===strip(normalize(b))}

async function boot(){await appReady;if(!firebaseConfig.enabled){setStatus('offline','סנכרון ענן עדיין לא הוגדר');renderAccount();return}try{const [appMod,authMod,fireMod]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js')]);api={...authMod,...fireMod};const fb=appMod.initializeApp(firebaseConfig);auth=authMod.getAuth(fb);db=fireMod.initializeFirestore(fb,{localCache:fireMod.persistentLocalCache({tabManager:fireMod.persistentMultipleTabManager()})});authMod.onAuthStateChanged(auth,handleUser);window.addEventListener('online',()=>{if(user&&pending)syncNow()});window.addEventListener('offline',()=>setStatus('offline',statusFor('offline')))}catch(e){lastError=e.message;setStatus('error',statusFor('error'));renderAccount()}}
function stateRef(uid=user.uid){return api.doc(db,'users',uid,'state','main')}
async function handleUser(next){unsubscribe?.();unsubscribe=null;user=next;initialized=false;pendingMigration=null;if(!user){setStatus(navigator.onLine?'offline':'offline',navigator.onLine?'לא מחובר לחשבון':statusFor('offline'));renderAccount();return}setStatus('syncing',statusFor('syncing'));try{const snap=await api.getDoc(stateRef()),local=window.EAApp.getData(),cloud=snap.exists()?snap.data().payload:null,linked=local.syncMeta?.uid===user.uid;if(cloud&&meaningful(local)&&!linked){pendingMigration={local,cloud};showMerge();return}if(!cloud&&meaningful(local)&&!linked){pendingMigration={local,cloud:null};renderAccount();setStatus('pending',statusFor('pending'));return}if(cloud&&!meaningful(local))window.EAApp.applySyncedData({...normalize(cloud),syncMeta:{uid:user.uid}});else if(cloud){const merged=mergeStates(local,cloud);window.EAApp.applySyncedData({...merged,syncMeta:{...merged.syncMeta,uid:user.uid}});if(!same(merged,cloud))setPending(true)}initialized=true;listen();if(pending||localStorage.getItem(PENDING_KEY)==='1')await syncNow();else synced()}catch(e){fail(e)}}
function listen(){unsubscribe?.();unsubscribe=api.onSnapshot(stateRef(),{includeMetadataChanges:true},snap=>{if(!initialized||!snap.exists()||snap.metadata.hasPendingWrites)return;const cloud=snap.data().payload,local=window.EAApp.getData(),merged=mergeStates(local,cloud);if(!same(local,merged))window.EAApp.applySyncedData({...merged,syncMeta:{...merged.syncMeta,uid:user.uid}});if(!same(cloud,merged))setPending(true);else synced()},fail)}
function synced(){pending=false;localStorage.removeItem(PENDING_KEY);localStorage.setItem(LAST_KEY,nowIso());setStatus('synced',statusFor('synced'));renderAccount()}
function fail(e){lastError=e?.message||String(e);setStatus(navigator.onLine?'error':'offline',navigator.onLine?statusFor('error'):statusFor('offline'));renderAccount()}
async function syncNow(){if(!user)return renderAccount();if(!navigator.onLine){setPending(true);setStatus('offline',statusFor('offline'));return}clearTimeout(syncTimer);setStatus('syncing',statusFor('syncing'));try{const local=normalize(window.EAApp.getData());const merged=await api.runTransaction(db,async tx=>{const ref=stateRef(),snap=await tx.get(ref),cloud=snap.exists()?snap.data().payload:null,next=cloud?mergeStates(local,cloud):local,revision=(snap.data()?.revision||0)+1;next.syncMeta={...(next.syncMeta||{}),uid:user.uid,revision,deviceId};tx.set(ref,{schemaVersion:3,revision,deviceId,payload:next,updatedAt:api.serverTimestamp()});return next});window.EAApp.applySyncedData({...merged,syncMeta:{...merged.syncMeta,uid:user.uid}});synced()}catch(e){setPending(true);fail(e)}}
function markDirty(){if(!firebaseConfig.enabled){setStatus('offline','סנכרון ענן עדיין לא הוגדר');return}setPending(true);if(user&&initialized&&navigator.onLine){clearTimeout(syncTimer);syncTimer=setTimeout(syncNow,900)}}
async function signIn(){if(!auth)return;try{await api.signInWithPopup(auth,new api.GoogleAuthProvider())}catch(e){if(e.code!=='auth/popup-closed-by-user')fail(e)}}
async function signOut(){unsubscribe?.();unsubscribe=null;initialized=false;await api.signOut(auth)}
async function chooseMigration(choice){if(!pendingMigration)return;if(choice==='cancel'){document.querySelector('#mergeModal').classList.remove('open');await signOut();return}let next;if(choice==='merge')next=mergeStates(pendingMigration.local,pendingMigration.cloud);if(choice==='local')next=normalize(pendingMigration.local);if(choice==='cloud')next=normalize(pendingMigration.cloud);next.syncMeta={...(next.syncMeta||{}),uid:user.uid};window.EAApp.applySyncedData(next);pendingMigration=null;document.querySelector('#mergeModal').classList.remove('open');initialized=true;listen();setPending(true);await syncNow()}
function showMerge(){document.querySelector('#mergeModal').classList.add('open');document.querySelectorAll('[data-merge]').forEach(b=>b.onclick=()=>chooseMigration(b.dataset.merge))}
async function uploadExisting(){const next=normalize(pendingMigration.local);next.syncMeta={...(next.syncMeta||{}),uid:user.uid};window.EAApp.applySyncedData(next);pendingMigration=null;initialized=true;listen();setPending(true);await syncNow()}
async function useEmptyCloud(){const fresh={lang:'he',selected:crypto.randomUUID(),profiles:[],settings:{},deletedProfiles:{},syncMeta:{uid:user.uid}};fresh.profiles=[{id:fresh.selected,name:'ילד/ה',updatedAt:Date.now(),p:{xp:0,completed:[],mistakes:[],activity:[],awards:{},study:{},lastDay:'',streak:0}}];window.EAApp.applySyncedData(fresh);pendingMigration=null;initialized=true;listen();setPending(true);await syncNow()}
async function deleteCloud(){if(!user)return;const answer=prompt('למחיקת נתוני הענן הקלידו מחיקה. גיבוי שחזור יישמר בענן למשך הזמן שתבחרו להשאירו.');if(answer!=='מחיקה')return;try{setStatus('syncing',statusFor('syncing'));await api.runTransaction(db,async tx=>{const ref=stateRef(),snap=await tx.get(ref),backup=api.doc(db,'users',user.uid,'backups',`deleted-${Date.now()}`);if(snap.exists())tx.set(backup,{...snap.data(),backupReason:'user-delete',createdAt:api.serverTimestamp()});tx.delete(ref)});window.EAApp.showToast('נתוני הענן נמחקו. הגיבוי המקומי נשאר במכשיר.');setPending(false);renderAccount()}catch(e){fail(e)}}
function renderAccount(){const body=$('#accountBody');if(!body)return;body.replaceChildren();const p=document.createElement('p');p.textContent='הסנכרון שומר את נתוני הלמידה בחשבון Google של ההורה. הגישה מוגנת באמצעות כניסה וכללי Firestore, לא באמצעות הסתרת הגדרות Firebase.';body.append(p);if(!firebaseConfig.enabled){const n=document.createElement('div');n.className='notice';n.textContent='Firebase עדיין לא הוגדר. האפליקציה ממשיכה לעבוד מקומית ובמצב לא מקוון. יש להשלים את FIREBASE_SETUP_HE.md.';body.append(n);return}if(!user){const b=document.createElement('button');b.className='primary';b.textContent='כניסה עם Google';b.onclick=signIn;body.append(b);return}const card=document.createElement('div');card.className='account-card';const photo=document.createElement('div');photo.className='account-photo';if(user.photoURL){const img=document.createElement('img');img.src=user.photoURL;img.alt='';photo.append(img)}else photo.textContent='👤';const info=document.createElement('div'),name=document.createElement('strong'),email=document.createElement('div');name.textContent=user.displayName||'חשבון Google';email.textContent=user.email||'';info.append(name,email);card.append(photo,info);body.append(card);if(pendingMigration&&!pendingMigration.cloud){const n=document.createElement('div');n.className='notice';n.textContent='נמצאה התקדמות מקומית. האם להעלות אותה לחשבון הענן? שום מידע לא יידרס בשקט.';const yes=document.createElement('button');yes.className='primary';yes.textContent='העלאת ההתקדמות הקיימת';yes.onclick=uploadExisting;const fresh=document.createElement('button');fresh.className='btn';fresh.textContent='להתחיל חשבון ענן ריק';fresh.onclick=useEmptyCloud;body.append(n,yes,fresh)}const last=document.createElement('p');last.className='sync-details';const stamp=localStorage.getItem(LAST_KEY);last.textContent=stamp?`סנכרון מוצלח אחרון: ${new Date(stamp).toLocaleString('he-IL')}`:'עדיין לא בוצע סנכרון מוצלח';body.append(last);const controls=document.createElement('div');controls.className='phrase-actions';[['סנכרון עכשיו',syncNow,'primary'],['ייצוא גיבוי',()=>window.EAApp.exportData(),'btn'],['החלפת חשבון',async()=>{await signOut();await signIn()},'btn'],['יציאה',signOut,'btn'],['מחיקת נתוני ענן',deleteCloud,'danger']].forEach(([text,fn,cls])=>{const b=document.createElement('button');b.className=cls;b.textContent=text;b.onclick=fn;controls.append(b)});body.append(controls);if(lastError){const err=document.createElement('p');err.className='notice';err.textContent=`שגיאת סנכרון: ${lastError}`;body.append(err)}}

window.EASync={markDirty,syncNow,renderAccount,mergeStates,getUser:()=>user?{uid:user.uid,email:user.email,displayName:user.displayName}:null,getIdToken:async()=>user?user.getIdToken():null};pending=localStorage.getItem(PENDING_KEY)==='1';setStatus(navigator.onLine?(pending?'pending':'offline'):'offline',navigator.onLine?(pending?statusFor('pending'):'לא מחובר לחשבון'):statusFor('offline'));boot();
