(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.EANaturalVoice=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
  const STATES=['teacherSpeaking','waitingForChild','childSpeaking','validating','correcting','praising','paused','disconnected'],RATES={greeting:1,newWord:.76,instruction:.88,pronunciation:.62,repeat:.72,hebrew:.9,celebration:1.03,goodbye:.94},STATE_HE={teacherSpeaking:'המורה מדבר',waitingForChild:'עכשיו תורך',childSpeaking:'מקשיב לך',validating:'בודק את התשובה',correcting:'מתרגלים יחד',praising:'כל הכבוד!',paused:'מושהה',disconnected:'ממתין'};
  const clamp=(n,a,b,f)=>Number.isFinite(Number(n))?Math.min(b,Math.max(a,Number(n))):f;
  function voiceScore(v,lang){const target=String(lang||'en-US').toLowerCase(),vl=String(v.lang||'').toLowerCase();let n=vl===target?50:vl.split('-')[0]===target.split('-')[0]?30:0;if(v.localService)n+=25;if(v.default)n+=8;if(/natural|premium|enhanced|neural|siri|google|microsoft|samantha|daniel|aria|jenny/i.test(v.name||''))n+=22;if(/compact|espeak|robot|basic/i.test(v.name||''))n-=15;return n}
  const VOICE_PREFERENCES={
    female:{he:['Hila','Carmit','Yael','Sivan','Microsoft Hila','Google עברית'],en:['Samantha','Ava','Aria','Jenny','Zira','Victoria','Karen','Moira','Susan','Hazel','Nicky','Shelley']},
    male:{he:['Asaf','Avri','Eitan','Lior','Microsoft Asaf','Google עברית גבר'],en:['Daniel','David','Guy','Aaron','Alex','Arthur','Fred','Tom','Mark','George','James','Ryan','Christopher']}
  };
  const normalizeGender=value=>({girl:'female',woman:'female',female:'female',boy:'male',man:'male',male:'male'}[String(value||'').toLowerCase()]||'not-specified');
  function voiceGender(v){if(v?.gender)return normalizeGender(v.gender);const value=`${v?.name||''} ${v?.voiceURI||''}`.toLowerCase();if(/daniel|david|guy|asaf|avri|eitan|lior|aaron|arthur|fred|tom|mark|george|james|ryan|christopher|\bmale\b|\bboy\b|גבר|בן/.test(value))return'male';if(/samantha|aria|jenny|zira|hila|carmit|yael|sivan|ava|victoria|karen|moira|susan|hazel|nicky|shelley|\bfemale\b|\bgirl\b|אישה|בת/.test(value))return'female';return'not-specified'}
  function preferenceIndex(v,lang,gender){const list=VOICE_PREFERENCES[normalizeGender(gender)]?.[String(lang).toLowerCase().startsWith('he')?'he':'en']||[],value=`${v?.name||''} ${v?.voiceURI||''}`.toLowerCase(),index=list.findIndex(name=>value.includes(name.toLowerCase()));return index<0?0:Math.max(4,20-index)}
  function rankVoices(voices,lang,gender='not-specified'){const targetGender=normalizeGender(gender);return[...(voices||[])].filter(v=>String(v.lang||'').toLowerCase().startsWith(String(lang).slice(0,2).toLowerCase())).sort((a,b)=>{const score=v=>{const detected=voiceGender(v),genderScore=targetGender==='not-specified'?0:detected===targetGender?28:detected==='not-specified'?0:-24;return voiceScore(v,lang)+preferenceIndex(v,lang,targetGender)+genderScore};return score(b)-score(a)||String(a.name).localeCompare(String(b.name))})}
  function chooseVoice(voices,lang,preferred='',gender='not-specified'){const targetGender=normalizeGender(gender),available=rankVoices(voices,lang,targetGender),manual=available.find(v=>(v.voiceURI===preferred||v.name===preferred)&&(targetGender==='not-specified'||voiceGender(v)===targetGender)),matched=targetGender==='not-specified'?null:available.find(v=>voiceGender(v)===targetGender),voice=manual||matched||available[0]||null,actual=voiceGender(voice),fallbackReason=!voice?'no-language-voice':actual===targetGender?'matched-gender':actual==='not-specified'?'gender-unknown-pitch-adjusted':'opposite-gender-pitch-adjusted';return{voice,basic:!!voice&&voiceScore(voice,lang)<55,available,requestedGender:targetGender,actualGender:actual,fallbackReason}}
  function genderPitch(gender,actualGender='not-specified'){const requested=normalizeGender(gender),actual=normalizeGender(actualGender);if(requested==='female')return actual==='female'?1.04:actual==='male'?1.24:1.18;if(requested==='male')return actual==='male'?.96:actual==='female'?.78:.84;return 1}
  function applyVoiceIdentity(utterance,{voices=[],lang='en-US',preferred='',gender='not-specified',pitch,rate,volume}={}){const choice=chooseVoice(voices,lang,preferred,gender);utterance.lang=lang;if(choice.voice)utterance.voice=choice.voice;utterance.pitch=clamp(pitch,.72,1.28,genderPitch(gender,choice.actualGender));if(rate!=null)utterance.rate=clamp(rate,.5,1.3,.88);if(volume!=null)utterance.volume=clamp(volume,0,1,1);return choice}
  function decodeEntities(text){return String(text).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,' and ').replace(/&quot;|&#34;/gi,'"').replace(/&apos;|&#39;/gi,"'").replace(/&lt;/gi,' ').replace(/&gt;/gi,' ')}
  function normalizeTextForSpeech(input,language='',options={}){
    const item=input&&typeof input==='object'?input:{text:input};
    if(item.speechText!=null||item.spokenText!=null)return normalizeTextForSpeech(String(item.speechText??item.spokenText),language,{...options,allowSymbols:options.allowSymbols||item.allowSymbols||item.teachesSymbols,explicit:true});
    let text=decodeEntities(item.text??item.displayText??'').replace(/<[^>]*>/g,' ');
    const allowSymbols=options.allowSymbols||item.allowSymbols||item.teachesSymbols;
    text=text.replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/```[\s\S]*?```/g,' ').replace(/`([^`]*)`/g,'$1');
    text=text.replace(/\b(?:https?|ftp):\/\/[^\s]+/gi,' ').replace(/\bwww\.[^\s]+/gi,' ');
    text=text.replace(/\b[A-Za-z]:\\(?:[^\\\s]+\\)*[^\\\s]*/g,' ').replace(/(?:^|\s)\/(?:[^/\s]+\/)+[^/\s]*/g,' ');
    text=text.replace(/[*#~^]+/g,' ').replace(/_+/g,' ').replace(/([A-Za-z0-9])[-–—]([A-Za-z0-9])/g,'$1 $2');
    if(!allowSymbols){
      text=text.replace(/\s*[/\\|]+\s*/g,', ').replace(/[()[\]{}<>]/g,' ').replace(/\b(?:backslash|underscore|pipe|asterisk|hash|open parenthesis|close parenthesis|slash)\b/gi,' ');
      try{text=text.replace(/\p{Extended_Pictographic}/gu,' ')}catch{}
    }
    text=text.replace(/([!?.,])\1+/g,'$1').replace(/\s+([!?.,])/g,'$1').replace(/([!?.,])(?=[A-Za-z\u0590-\u05ff])/g,'$1 ').replace(/,\s*,+/g,', ').replace(/\s+/g,' ').trim();
    if(text&&!/[.!?]$/.test(text)&&/[\u0590-\u05ff]/.test(text)&&/[A-Za-z]/.test(text))text+='.';
    const debug=!!(root?.EA_DEV_MODE||root?.EAApp?.getData?.()?.settings?.teacherAI?.developerDebug);
    if(debug)console.debug('[speech-normalized]',{language,text});
    return text;
  }
  const toSpokenText=(input,options={})=>normalizeTextForSpeech(input,options.language||'',options);
  function splitPhrases(text,language=''){return normalizeTextForSpeech(text,language).split(/(?<=[.!?])\s+|\s*;\s*/).map(x=>x.trim()).filter(Boolean)}
  function splitSpeechSegments(input,defaultLanguage='en-US'){
    const normalized=normalizeTextForSpeech(input,defaultLanguage);
    const segments=[];
    for(const phrase of splitPhrases(normalized,defaultLanguage)){
      const parts=phrase.match(/[\u0590-\u05ff][\u0590-\u05ff\s'"׳״.,!?-]*|[^\u0590-\u05ff]+/g)||[];
      for(const raw of parts){
        const text=normalizeTextForSpeech(raw,/[\u0590-\u05ff]/.test(raw)?'he-IL':defaultLanguage);
        if(text)segments.push({text,lang:/[\u0590-\u05ff]/.test(text)?'he-IL':defaultLanguage});
      }
    }
    return segments;
  }
  function pronunciationMeta(text,p={}){const displayText=p.displayText||text,spokenText=normalizeTextForSpeech(p.speechText??p.spokenText??text,'en-US',{allowSymbols:p.teachesSymbols}),naturalPronunciation=normalizeTextForSpeech(p.naturalPronunciation||spokenText,'en-US',{allowSymbols:p.teachesSymbols}),words=spokenText.replace(/[.!?]/g,'').split(/\s+/).filter(Boolean);return{displayText,spokenText,naturalPronunciation,slowPronunciation:normalizeTextForSpeech(p.slowPronunciation||naturalPronunciation,'en-US',{allowSymbols:p.teachesSymbols}),pronunciationChunks:p.pronunciationChunks?.length?p.pronunciationChunks.map(x=>normalizeTextForSpeech(x,'en-US',{allowSymbols:p.teachesSymbols})):(words.length===1?[naturalPronunciation]:words),stressHint:p.stressHint||'',commonRecognitionVariants:p.commonRecognitionVariants||[]}}
  function responseStyle({category,correctStreak=0,attempts=0,hadDifficulty=false,index=0}={}){const pick=a=>a[Math.abs(index)%a.length];if(category==='correct'){if(hadDifficulty||attempts>1)return{state:'praising',text:'Yes! You worked it out.',tone:'celebration'};if(correctStreak>=3)return{state:'praising',text:"Wow, you're getting really good at this.",tone:'celebration'};return{state:'praising',text:pick(["That's right!",'Exactly!','You got it!','Great job!']),tone:'celebration'}}if(category==='almost-correct')return{state:'correcting',text:pick(["You're very close. Listen once more.","Almost! Let's say it slowly together."]),tone:'repeat'};if(category==='speech-recognition-uncertain')return{state:'correcting',text:"I'm not sure I heard that clearly. Could you say it one more time?",tone:'repeat'};if(category==='didnt-answer')return{state:'waitingForChild',text:"That's okay. Take your time.",tone:'instruction'};return{state:'correcting',text:pick(["Good effort, but that's not the answer yet. Let's look again.","Let's look again. Here's a small hint."]),tone:'instruction'}}
  class SpeechQueue{constructor({synth,Utterance,onState=()=>{},getSettings=()=>({}),pause=(ms)=>new Promise(r=>setTimeout(r,ms))}={}){this.synth=synth;this.Utterance=Utterance;this.onState=onState;this.getSettings=getSettings;this.pause=pause;this.token=0;this.active=false;this.last=null;this.voices=[]}setVoices(v){this.voices=[...(v||[])]}cancel(){this.token++;this.active=false;this.synth?.cancel?.()}async speak(items,{priority=false}={}){if(priority)this.cancel();const token=++this.token;this.synth?.cancel?.();this.active=true;this.onState('teacherSpeaking');const list=(Array.isArray(items)?items:[{text:items}]).flatMap(x=>splitSpeechSegments(x.text,x.lang||'en-US').map(segment=>({...x,...segment})));this.last=list;for(const item of list){if(token!==this.token)break;await this.one(item,token);if(token!==this.token)break;await this.pause(clamp(item.pauseAfter,0,3000,item.question?650:280))}if(token===this.token){this.active=false;this.onState('waitingForChild')}return token===this.token}one(item,token){return new Promise(resolve=>{if(!this.synth||!this.Utterance)return resolve();const lang=item.lang||'en-US',speechText=normalizeTextForSpeech(item.text,lang,item),u=new this.Utterance(speechText),s=this.getSettings(),teacherGender=s.teacherVoiceGender||s.childGender||'not-specified',selected=lang.startsWith('he')?s.hebrewVoice:s.englishVoice,choice=chooseVoice(this.voices,lang,selected,teacherGender);u.lang=lang;if(choice.voice)u.voice=choice.voice;const mult={slow:.82,normal:1,natural:1.08}[s.speechSpeed]||1;u.rate=clamp(item.rate||(RATES[item.tone]||RATES.instruction)*mult,.5,1.2,.88);const expressive=item.tone==='celebration'?1.03:1;u.pitch=clamp(item.pitch,.72,1.28,genderPitch(teacherGender,choice.actualGender)*expressive);u.volume=clamp(s.speechVolume,0,1,1);if(s.developerDebug)console.debug('[EA Voice Utterance]',{lang,teacherGender,voice:choice.voice?.name||null,actualGender:choice.actualGender,pitch:u.pitch,fallback:choice.fallbackReason});let done=false;const end=()=>{if(done)return;done=true;resolve()};u.onend=end;u.onerror=end;if(token!==this.token||!speechText)return end();this.synth.speak(u)})}repeatSlower(){if(!this.last)return Promise.resolve(false);return this.speak(this.last.map(x=>({...x,tone:'repeat',rate:(x.rate||RATES[x.tone]||.88)*.78})),{priority:true})}}
  function createTurnGuard(){let speaking=false,listening=false,answerHandled=false,generation=0;return{beginSpeech(){generation++;speaking=true;listening=false;answerHandled=false;return generation},endSpeech(id){if(id!==generation)return false;speaking=false;return true},beginListening(){if(speaking||listening)return false;listening=true;answerHandled=false;return true},handleAnswer(){if(!listening||answerHandled)return false;answerHandled=true;listening=false;return true},interrupt(){generation++;speaking=false;listening=false;answerHandled=false},snapshot(){return{speaking,listening,answerHandled,generation}}}}
  return{STATES,STATE_HE,RATES,VOICE_PREFERENCES,normalizeGender,voiceScore,voiceGender,rankVoices,chooseVoice,genderPitch,applyVoiceIdentity,normalizeTextForSpeech,toSpokenText,splitPhrases,splitSpeechSegments,pronunciationMeta,responseStyle,SpeechQueue,createTurnGuard};
});
