(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EANaturalVoice=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const STATES=['teacherSpeaking','waitingForChild','childSpeaking','validating','correcting','praising','paused','disconnected'],RATES={greeting:1,newWord:.76,instruction:.88,pronunciation:.62,repeat:.72,hebrew:.9,celebration:1.03,goodbye:.94},STATE_HE={teacherSpeaking:'המורה מדבר',waitingForChild:'עכשיו תורך',childSpeaking:'מקשיב לך',validating:'בודק את התשובה',correcting:'מתרגלים יחד',praising:'כל הכבוד!',paused:'מושהה',disconnected:'ממתין'};
  const clamp=(n,a,b,f)=>Number.isFinite(Number(n))?Math.min(b,Math.max(a,Number(n))):f;
  function voiceScore(v,lang){const target=String(lang||'en-US').toLowerCase(),vl=String(v.lang||'').toLowerCase();let n=vl===target?50:vl.split('-')[0]===target.split('-')[0]?30:0;if(v.localService)n+=25;if(v.default)n+=8;if(/natural|premium|enhanced|neural|siri|google|microsoft|samantha|daniel|aria|jenny/i.test(v.name||''))n+=22;if(/compact|espeak|robot|basic/i.test(v.name||''))n-=15;return n}
  function voiceGender(v){const value=`${v?.name||''} ${v?.voiceURI||''}`.toLowerCase();if(/daniel|david|guy|\bmale\b|\bboy\b|גבר|בן/.test(value))return'boy';if(/samantha|aria|jenny|zira|\bfemale\b|\bgirl\b|אישה|בת/.test(value))return'girl';return'not-specified'}
  function rankVoices(voices,lang,gender='not-specified'){return[...(voices||[])].filter(v=>String(v.lang||'').toLowerCase().startsWith(String(lang).slice(0,2).toLowerCase())).sort((a,b)=>{const quality=voiceScore(b,lang)-voiceScore(a,lang);if(Math.abs(quality)>18)return quality;const match=(voiceGender(b)===gender?12:0)-(voiceGender(a)===gender?12:0);return match||quality||String(a.name).localeCompare(String(b.name))})}
  function chooseVoice(voices,lang,preferred='',gender='not-specified'){const available=rankVoices(voices,lang,gender),voice=available.find(v=>v.voiceURI===preferred||v.name===preferred)||available[0]||null;return{voice,basic:!!voice&&voiceScore(voice,lang)<55,available}}
  function decodeEntities(text){return String(text).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,' and ').replace(/&quot;|&#34;/gi,'"').replace(/&apos;|&#39;/gi,"'").replace(/&lt;/gi,' ').replace(/&gt;/gi,' ')}
  function toSpokenText(input,options={}){
    const item=input&&typeof input==='object'?input:{text:input};
    if(item.spokenText!=null)return toSpokenText(String(item.spokenText),{...options,allowSymbols:options.allowSymbols||item.allowSymbols||item.teachesSymbols,explicit:true});
    let text=decodeEntities(item.text??item.displayText??'').replace(/<[^>]*>/g,' ');
    const allowSymbols=options.allowSymbols||item.allowSymbols||item.teachesSymbols;
    text=text.replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/```[\s\S]*?```/g,' ').replace(/`([^`]*)`/g,'$1');
    text=text.replace(/[*#~^]+/g,' ').replace(/_+/g,' ').replace(/([A-Za-z0-9])[-–—]([A-Za-z0-9])/g,'$1 $2');
    if(!allowSymbols)text=text.replace(/\s*[/\\|]+\s*/g,' or ').replace(/[()[\]{}<>]/g,' ').replace(/\b(?:backslash|underscore|pipe|asterisk|hash|open parenthesis|close parenthesis|slash)\b/gi,' ');
    return text.replace(/([!?.,])\1+/g,'$1').replace(/\s+([!?.,])/g,'$1').replace(/([!?.,])(?=[A-Za-z\u0590-\u05ff])/g,'$1 ').replace(/\s+/g,' ').trim();
  }
  function splitPhrases(text){return toSpokenText(text).split(/(?<=[.!?])\s+|\s*;\s*/).map(x=>x.trim()).filter(Boolean)}
  function pronunciationMeta(text,p={}){const displayText=p.displayText||text,spokenText=toSpokenText(p.spokenText??text,{allowSymbols:p.teachesSymbols}),naturalPronunciation=toSpokenText(p.naturalPronunciation||spokenText,{allowSymbols:p.teachesSymbols}),words=spokenText.replace(/[.!?]/g,'').split(/\s+/).filter(Boolean);return{displayText,spokenText,naturalPronunciation,slowPronunciation:toSpokenText(p.slowPronunciation||naturalPronunciation,{allowSymbols:p.teachesSymbols}),pronunciationChunks:p.pronunciationChunks?.length?p.pronunciationChunks.map(x=>toSpokenText(x,{allowSymbols:p.teachesSymbols})):(words.length===1?[naturalPronunciation]:words),stressHint:p.stressHint||'',commonRecognitionVariants:p.commonRecognitionVariants||[]}}
  function responseStyle({category,correctStreak=0,attempts=0,hadDifficulty=false,index=0}={}){const pick=a=>a[Math.abs(index)%a.length];if(category==='correct'){if(hadDifficulty||attempts>1)return{state:'praising',text:'Yes! You worked it out.',tone:'celebration'};if(correctStreak>=3)return{state:'praising',text:"Wow, you're getting really good at this.",tone:'celebration'};return{state:'praising',text:pick(["That's right!",'Exactly!','You got it!','Great job!']),tone:'celebration'}}if(category==='almost-correct')return{state:'correcting',text:pick(["You're very close. Listen once more.","Almost! Let's say it slowly together."]),tone:'repeat'};if(category==='speech-recognition-uncertain')return{state:'correcting',text:"I'm not sure I heard that clearly. Could you say it one more time?",tone:'repeat'};if(category==='didnt-answer')return{state:'waitingForChild',text:"That's okay. Take your time.",tone:'instruction'};return{state:'correcting',text:pick(["Good effort, but that's not the answer yet. Let's look again.","Let's look again. Here's a small hint."]),tone:'instruction'}}
  class SpeechQueue{constructor({synth,Utterance,onState=()=>{},getSettings=()=>({}),pause=(ms)=>new Promise(r=>setTimeout(r,ms))}={}){this.synth=synth;this.Utterance=Utterance;this.onState=onState;this.getSettings=getSettings;this.pause=pause;this.token=0;this.active=false;this.last=null;this.voices=[]}setVoices(v){this.voices=[...(v||[])]}cancel(){this.token++;this.active=false;this.synth?.cancel?.()}async speak(items,{priority=false}={}){if(priority)this.cancel();const token=++this.token;this.synth?.cancel?.();this.active=true;this.onState('teacherSpeaking');const list=(Array.isArray(items)?items:[{text:items}]).flatMap(x=>splitPhrases(x.text).map(text=>({...x,text})));this.last=list;for(const item of list){if(token!==this.token)break;await this.one(item,token);if(token!==this.token)break;await this.pause(clamp(item.pauseAfter,0,3000,item.question?650:280))}if(token===this.token){this.active=false;this.onState('waitingForChild')}return token===this.token}one(item,token){return new Promise(resolve=>{if(!this.synth||!this.Utterance)return resolve();const lang=item.lang||'en-US',u=new this.Utterance(item.text),s=this.getSettings(),selected=lang.startsWith('he')?s.hebrewVoice:s.englishVoice,choice=chooseVoice(this.voices,lang,selected,s.childGender);u.lang=lang;if(choice.voice)u.voice=choice.voice;const mult={slow:.82,normal:1,natural:1.08}[s.speechSpeed]||1;u.rate=clamp(item.rate||(RATES[item.tone]||RATES.instruction)*mult,.5,1.2,.88);u.pitch=clamp(item.pitch,.8,1.2,item.tone==='celebration'?1.06:1);u.volume=clamp(s.speechVolume,0,1,1);let done=false;const end=()=>{if(done)return;done=true;resolve()};u.onend=end;u.onerror=end;if(token!==this.token)return end();this.synth.speak(u)})}repeatSlower(){if(!this.last)return Promise.resolve(false);return this.speak(this.last.map(x=>({...x,tone:'repeat',rate:(x.rate||RATES[x.tone]||.88)*.78})),{priority:true})}}
  function createTurnGuard(){let speaking=false,listening=false,answerHandled=false,generation=0;return{beginSpeech(){generation++;speaking=true;listening=false;answerHandled=false;return generation},endSpeech(id){if(id!==generation)return false;speaking=false;return true},beginListening(){if(speaking||listening)return false;listening=true;answerHandled=false;return true},handleAnswer(){if(!listening||answerHandled)return false;answerHandled=true;listening=false;return true},interrupt(){generation++;speaking=false;listening=false;answerHandled=false},snapshot(){return{speaking,listening,answerHandled,generation}}}}
  return{STATES,STATE_HE,RATES,voiceScore,voiceGender,rankVoices,chooseVoice,toSpokenText,splitPhrases,pronunciationMeta,responseStyle,SpeechQueue,createTurnGuard};
});
