(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EATeacherVisual=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const STATES=['idle','greeting','speaking','listening','thinking','explaining','pointing','praising','correcting','celebrating','surprised','waiting','paused','uncertain','goodbye','waving','happy','encouraging'];
  const STATE_LABELS={idle:'המורה מוכן/ה',greeting:'המורה מברך/ת',speaking:'המורה מדבר/ת',listening:'המורה מקשיב/ה',thinking:'המורה חושב/ת',explaining:'המורה מסביר/ה',pointing:'המורה מצביע/ה על הפעילות',praising:'המורה מחייך/ת ומהנהן/ת',correcting:'המורה עוזר/ת בעדינות',celebrating:'המורה מוחא/ת כפיים וחוגג/ת',surprised:'המורה מופתע/ת לטובה',waiting:'המורה ממתין/ה בסבלנות',paused:'השיעור מושהה',uncertain:'המורה לא שמע/ה בבירור',goodbye:'המורה נפרד/ת',waving:'המורה מנופף/ת לשלום',happy:'המורה שמח/ה',encouraging:'המורה מעודד/ת ומכוון/ת אל הפעילות'};
  const GENDER_LABELS={
    female:{idle:'אמילי מוכנה',greeting:'אמילי מברכת אותך',speaking:'אמילי מדברת',listening:'אמילי מקשיבה',thinking:'אמילי חושבת',explaining:'אמילי מסבירה',pointing:'אמילי מצביעה על הפעילות',praising:'אמילי מחייכת ומהנהנת',correcting:'אמילי עוזרת בעדינות',celebrating:'אמילי מוחאת כפיים וחוגגת',surprised:'אמילי מופתעת לטובה',waiting:'אמילי ממתינה בסבלנות',paused:'השיעור מושהה',uncertain:'אמילי לא שמעה בבירור',goodbye:'אמילי נפרדת',waving:'אמילי מנופפת לשלום',happy:'אמילי שמחה',encouraging:'אמילי מעודדת ומכוונת אל הפעילות'},
    male:{idle:'אדם מוכן',greeting:'אדם מברך אותך',speaking:'אדם מדבר',listening:'אדם מקשיב',thinking:'אדם חושב',explaining:'אדם מסביר',pointing:'אדם מצביע על הפעילות',praising:'אדם מחייך ומהנהן',correcting:'אדם עוזר בעדינות',celebrating:'אדם מוחא כפיים וחוגג',surprised:'אדם מופתע לטובה',waiting:'אדם ממתין בסבלנות',paused:'השיעור מושהה',uncertain:'אדם לא שמע בבירור',goodbye:'אדם נפרד',waving:'אדם מנופף לשלום',happy:'אדם שמח',encouraging:'אדם מעודד ומכוון אל הפעילות'}
  };
  const REACTIONS={correct:'praising','almost-correct':'correcting','wrong-related':'pointing','completely-unrelated':'correcting','didnt-answer':'waiting','speech-recognition-uncertain':'uncertain'};
  function stateFor(category,streak=0){return category==='correct'&&streak>=3?'celebrating':REACTIONS[category]||'thinking'}
  let visualInstance=0;
  function characterSvg(character='female-young'){const uid=`teacher-${character}-${++visualInstance}`,isMale=['male-young','daniel'].includes(character),c=isMale?{skin:'#b98060',shadow:'#925d45',hair:'#2b201e',jacket:'#27766f',jacketDark:'#214f58',shirt:'#f2fbf8',eye:'#35251f',lip:'#75423f'}:{skin:'#d7a082',shadow:'#b97860',hair:'#54342f',jacket:'#a84f82',jacketDark:'#713b6c',shirt:'#fff7f4',eye:'#51342f',lip:'#b44f69'};return `<svg class="teacher-svg ${isMale?'teacher-male-asset':'teacher-female-asset'}" data-dedicated-asset="${isMale?'male-teacher':'female-teacher'}" viewBox="0 0 280 390" role="img" aria-label="${isMale?'אדם, מורה צעיר, ידידותי ומקצועי':'אמילי, מורה צעירה, ידידותית ומקצועית'}">
    <defs><linearGradient id="skin-${uid}" x1="0" x2="1"><stop stop-color="${c.skin}"/><stop offset="1" stop-color="${c.shadow}"/></linearGradient><linearGradient id="jacket-${uid}" y2="1"><stop stop-color="${c.jacket}"/><stop offset="1" stop-color="${c.jacketDark}"/></linearGradient></defs>
    <g class="teacher-breath"><g class="teacher-body">${isMale?`<path fill="url(#jacket-${uid})" d="M43 389v-94c0-57 39-88 97-88s97 31 97 88v94z"/><path fill="${c.shirt}" d="M101 215l39 45 39-45 18 18-29 78h-56l-29-78z"/><path fill="#d9a441" d="M136 251h8l7 86-11 15-11-15z"/>`:`<path fill="url(#jacket-${uid})" d="M55 389v-91c0-55 34-86 85-86s85 31 85 86v91z"/><path fill="${c.shirt}" d="M91 230q49 38 98 0l-10 120H101z"/><path fill="none" stroke="#f2b7c8" stroke-width="6" d="M107 230q33 31 66 0"/><circle fill="#f5d2dc" cx="140" cy="263" r="5"/>`}</g>
    <g class="teacher-arm teacher-arm-left"><path fill="${c.jacket}" d="M72 263c-34 13-53 45-58 78l25 5c8-25 21-43 46-52z"/><g class="teacher-hand"><ellipse fill="${c.skin}" cx="26" cy="344" rx="17" ry="14"/><path stroke="${c.shadow}" stroke-width="2" d="M17 340l17 4M18 346l15 3"/></g></g>
    <g class="teacher-arm teacher-arm-right"><path fill="${c.jacket}" d="M208 263c34 13 53 45 58 78l-25 5c-8-25-21-43-46-52z"/><g class="teacher-hand"><ellipse fill="${c.skin}" cx="254" cy="344" rx="17" ry="14"/><path stroke="${c.shadow}" stroke-width="2" d="M246 340l17 4M247 346l15 3"/></g></g></g>
    <path class="teacher-neck" fill="${c.skin}" d="M116 186h48v44q-24 23-48 0z"/><g class="teacher-head"><ellipse fill="${c.shadow}" cx="76" cy="127" rx="10" ry="20"/><ellipse fill="${c.shadow}" cx="204" cy="127" rx="10" ry="20"/><path fill="url(#skin-${uid})" d="${isMale?'M75 105c0-59 27-88 65-88s65 29 65 88v38c0 47-29 75-65 75s-65-28-65-75z':'M82 105c0-57 24-88 58-88s58 31 58 88v37c0 48-25 76-58 76s-58-28-58-76z'}"/>
    ${isMale?`<path fill="${c.hair}" d="M74 111Q65 43 99 20q45-29 85 2 25 20 18 76l-12-36q-47 13-99-2z"/><path fill="${c.hair}" opacity=".82" d="M81 50q58-37 112 3l-11-24q-48-34-91 0z"/>`:`<path fill="${c.hair}" d="M73 116Q64 45 94 18q47-42 94-5 31 25 20 109l-14 67-20-13 12-101q-44 16-91-8l10 110-22 17z"/><path fill="${c.hair}" opacity=".7" d="M72 96q-14 72 5 126l28-18-11-136z"/><path fill="${c.hair}" opacity=".7" d="M205 91q16 73-3 131l-29-17 13-137z"/><path fill="#e8b7c5" d="M184 45q16 4 24 18-17-3-24-18"/>`}
    <g class="teacher-brows" fill="none" stroke="${c.hair}" stroke-width="5" stroke-linecap="round"><path d="M99 105q16-9 30 0"/><path d="M151 105q16-9 30 0"/></g>
    <g class="teacher-eye-group"><path fill="#fff" d="M96 119q16-13 32 0-16 18-32 0M152 119q16-13 32 0-16 18-32 0"/><g class="teacher-eyes" fill="${c.eye}"><ellipse cx="113" cy="119" rx="6" ry="8"/><ellipse cx="168" cy="119" rx="6" ry="8"/><circle fill="#fff" cx="115" cy="116" r="2"/><circle fill="#fff" cx="170" cy="116" r="2"/></g><g class="teacher-lids" fill="${c.skin}"><path d="M95 117q17-16 34 0-18-7-34 0"/><path d="M151 117q17-16 34 0-18-7-34 0"/></g></g>
    <path class="teacher-nose" fill="none" stroke="${c.shadow}" stroke-width="3" stroke-linecap="round" d="M140 119q-5 24 5 27l-8 3"/><path fill="#e39a8b" opacity=".28" d="M89 144q13-8 25 1-13 8-25-1M166 145q13-9 25-1-12 8-25 1"/>
    <g class="teacher-mouth"><path class="mouth-rest" fill="none" stroke="${c.lip}" stroke-width="4" stroke-linecap="round" d="M119 171q21 10 42 0"/><path class="mouth-smile" fill="${c.lip}" d="M116 168q24 22 48 0-23 38-48 0"/><ellipse class="mouth-talk mouth-a" fill="#5f2832" cx="140" cy="177" rx="17" ry="10"/><ellipse class="mouth-talk mouth-o" fill="#5f2832" cx="140" cy="177" rx="9" ry="14"/><path class="mouth-talk mouth-e" fill="#fff" stroke="${c.lip}" stroke-width="3" d="M119 174q21-8 42 0-20 17-42 0"/></g></g></svg>`}
  function createController(rootEl,{character='female-young',imageAsset='',reducedMotion=false,subtitles='all'}={}){let state='idle',mouthTimer=0,lastSpeech={text:'',lang:'en-US'},replay=()=>{};const gender=['male-young','daniel'].includes(character)?'male':'female',labels=GENDER_LABELS[gender],alt=gender==='male'?'אדם, מורה צעיר וידידותי':'אמילי, מורה צעירה וידידותית',photo=imageAsset?.startsWith?.('assets/'),portrait=photo?`<span class="teacher-photo-wrap" data-photo-character="${character}"><img class="teacher-photo teacher-photo-base" src="${imageAsset}" alt="${alt}"><i class="teacher-photo-speech" aria-hidden="true"></i><i class="teacher-photo-aura" aria-hidden="true"></i><span class="teacher-photo-stars" aria-hidden="true"><b>✦</b><b>★</b><b>✧</b></span></span>`:characterSvg(character);rootEl.innerHTML=`<section class="teacher-presence${photo?' teacher-presence-photo':''}" data-state="idle" data-character="${character}" aria-live="polite"><button class="teacher-character" type="button" aria-label="לחצו על המורה כדי לשמוע שוב">${portrait}<span class="teacher-ear" aria-label="הפעלת הקשבה">👂</span></button><div class="teacher-bubbles"><p class="speech-bubble en" lang="en"></p><p class="speech-bubble he" lang="he" dir="rtl"></p></div><span class="sr-only teacher-gesture">${labels.idle}</span></section>`;const presence=rootEl.querySelector('.teacher-presence'),en=rootEl.querySelector('.speech-bubble.en'),he=rootEl.querySelector('.speech-bubble.he');const stopMouth=()=>{clearInterval(mouthTimer);mouthTimer=0;presence.classList.remove('mouth-active');delete presence.dataset.mouth};const setState=next=>{state=STATES.includes(next)?next:'idle';presence.dataset.state=state;rootEl.querySelector('.teacher-gesture').textContent=labels[state];if(!['speaking','greeting','explaining','praising','celebrating'].includes(state))stopMouth();return state};const startMouth=()=>{if(reducedMotion)return;stopMouth();presence.classList.add('mouth-active');let n=0;presence.dataset.mouth='a';mouthTimer=setInterval(()=>presence.dataset.mouth=['a','o','e','a','rest'][++n%5],105+(n%3)*28)};const showSpeech=(text,lang='en-US')=>{lastSpeech={text,lang};const target=lang.startsWith('he')?he:en,other=target===en?he:en;target.textContent=text;target.hidden=subtitles==='replay'||(subtitles==='english-hidden'&&target===en);if(other.textContent&&subtitles!=='all')other.hidden=true};const reveal=()=>{(lastSpeech.lang.startsWith('he')?he:en).hidden=false};rootEl.querySelector('.teacher-character').onclick=()=>{reveal();replay(lastSpeech)};return{setState,startMouth,stopMouth,showSpeech,reveal,setReplay(fn){replay=fn||(()=>{})},getState:()=>state,getLastSpeech:()=>({...lastSpeech}),destroy(){stopMouth()}}}
  return{STATES,STATE_LABELS,GENDER_LABELS,REACTIONS,stateFor,characterSvg,createController};
});
