(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EATeacherVisual=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const STATES=['idle','greeting','speaking','listening','thinking','explaining','pointing','praising','correcting','celebrating','waiting','paused','uncertain','goodbye'];
  const STATE_LABELS={idle:'המורה מוכן/ה',greeting:'המורה מברך/ת',speaking:'המורה מדבר/ת',listening:'המורה מקשיב/ה',thinking:'המורה חושב/ת',explaining:'המורה מסביר/ה',pointing:'המורה מצביע/ה על הלוח',praising:'המורה מחייך/ת ומהנהן/ת',correcting:'המורה עוזר/ת בעדינות',celebrating:'המורה חוגג/ת',waiting:'המורה ממתין/ה בסבלנות',paused:'השיעור מושהה',uncertain:'המורה לא שמע/ה בבירור',goodbye:'המורה נפרד/ת'};
  const REACTIONS={correct:'praising','almost-correct':'correcting','wrong-related':'pointing','completely-unrelated':'correcting','didnt-answer':'waiting','speech-recognition-uncertain':'uncertain'};
  function stateFor(category,streak=0){return category==='correct'&&streak>=3?'celebrating':REACTIONS[category]||'thinking'}
  function characterSvg(character='noa'){const c=character==='daniel'?{skin:'#9b6748',hair:'#2c1d18',shirt:'#287a72',accent:'#ffd166'}:{skin:'#c98767',hair:'#513126',shirt:'#7257c7',accent:'#ff8fab'};return `<svg class="teacher-svg" viewBox="0 0 240 310" role="img" aria-label="דמות מורה ידידותית"><g class="teacher-body"><path fill="${c.shirt}" d="M55 300v-70c0-34 28-55 65-55s65 21 65 55v70z"/><path fill="#fff" d="M96 183l24 29 24-29 14 9-18 31h-40l-18-31z"/></g><g class="teacher-arm teacher-arm-left"><path fill="${c.shirt}" d="M68 205c-21 8-38 30-43 54l18 6c7-18 18-31 34-36z"/><circle fill="${c.skin}" cx="34" cy="264" r="12"/></g><g class="teacher-arm teacher-arm-right"><path fill="${c.shirt}" d="M172 205c22 8 38 30 43 54l-18 6c-7-18-18-31-34-36z"/><circle fill="${c.skin}" cx="206" cy="264" r="12"/></g><g class="teacher-head"><ellipse fill="${c.skin}" cx="120" cy="112" rx="64" ry="72"/><path fill="${c.hair}" d="M58 111c-9-66 34-91 69-85 38 5 61 34 54 84l-16-40c-26 8-61 6-88-5z"/><g class="teacher-brows" stroke="${c.hair}" stroke-width="5" stroke-linecap="round"><path d="M82 100q14-8 27 0"/><path d="M132 100q14-8 27 0"/></g><g class="teacher-eyes" fill="#211a18"><ellipse cx="96" cy="116" rx="6" ry="8"/><ellipse cx="145" cy="116" rx="6" ry="8"/></g><path class="teacher-mouth mouth-smile" fill="none" stroke="#8c3343" stroke-width="5" stroke-linecap="round" d="M101 145q19 18 39 0"/><ellipse class="teacher-mouth mouth-talk" fill="#742c3b" cx="120" cy="151" rx="13" ry="5"/></g><circle fill="${c.accent}" cx="120" cy="239" r="8"/></svg>`}
  function createController(rootEl,{character='noa',reducedMotion=false,subtitles='all'}={}){let state='idle',mouthTimer=0,lastSpeech={text:'',lang:'en-US'},replay=()=>{};rootEl.innerHTML=`<section class="teacher-presence" data-state="idle" data-character="${character}" aria-live="polite"><button class="teacher-character" type="button" aria-label="לחצו על המורה כדי לשמוע שוב">${characterSvg(character)}<span class="teacher-ear" aria-label="הפעלת הקשבה">👂</span></button><div class="teacher-bubbles"><p class="speech-bubble en" lang="en"></p><p class="speech-bubble he" lang="he" dir="rtl"></p></div><span class="sr-only teacher-gesture">${STATE_LABELS.idle}</span></section>`;const presence=rootEl.querySelector('.teacher-presence'),en=rootEl.querySelector('.speech-bubble.en'),he=rootEl.querySelector('.speech-bubble.he');const stopMouth=()=>{clearInterval(mouthTimer);mouthTimer=0;presence.classList.remove('mouth-active');presence.style.removeProperty('--mouth-step')};const setState=next=>{state=STATES.includes(next)?next:'idle';presence.dataset.state=state;rootEl.querySelector('.teacher-gesture').textContent=STATE_LABELS[state];if(!['speaking','greeting','explaining','praising','celebrating'].includes(state))stopMouth();return state};const startMouth=()=>{if(reducedMotion)return;stopMouth();presence.classList.add('mouth-active');let n=0;mouthTimer=setInterval(()=>presence.style.setProperty('--mouth-step',String(++n%3)),115)};const showSpeech=(text,lang='en-US')=>{lastSpeech={text,lang};const target=lang.startsWith('he')?he:en,other=target===en?he:en;target.textContent=text;target.hidden=subtitles==='replay'||(subtitles==='english-hidden'&&target===en);if(other.textContent&&subtitles!=='all')other.hidden=true};const reveal=()=>{(lastSpeech.lang.startsWith('he')?he:en).hidden=false};rootEl.querySelector('.teacher-character').onclick=()=>{reveal();replay(lastSpeech)};return{setState,startMouth,stopMouth,showSpeech,reveal,setReplay(fn){replay=fn||(()=>{})},getState:()=>state,getLastSpeech:()=>({...lastSpeech}),destroy(){stopMouth()}}}
  return{STATES,STATE_LABELS,REACTIONS,stateFor,characterSvg,createController};
});
