import {teacherAIConfig} from './firebase-config.js';

const Core=window.EATeacherCore,PHASES=['greeting','warm-up','teach-vocabulary','listen-repeat','comprehension','speaking','review','summary','goodbye'];
const PHASE_HE={greeting:'ברכה','warm-up':'חימום','teach-vocabulary':'לימוד מילים','listen-repeat':'הקשבה וחזרה',comprehension:'בדיקת הבנה',speaking:'תרגול דיבור',review:'חזרה',summary:'סיכום',goodbye:'פרידה'};
let settings={...Core.DEFAULTS},context=null,shared=null,selectedMode='free',phase=0,startedAt=0,transcript=[],words=[],review=[],correct=0,retries=0,hebrewUses=0,paused=false,muted=false,recognition=null,pc=null,dc=null,micStream=null,sessionId=null;
const $=s=>document.querySelector(s),ready=new Promise(r=>window.EAApp?r():window.addEventListener('ea-app-ready',r,{once:true}));

function styles(){const s=document.createElement('style');s.textContent=`.teacher-launch{background:linear-gradient(135deg,#148762,#5b4bd8);color:#fff;border:0;border-radius:999px;padding:.65rem 1rem;font-weight:850}.teacher-stage,.teacher-settings,.mode-settings{display:grid;gap:.9rem}.teacher-warning,.mode-note{padding:.85rem;border-radius:14px;background:#fff4d7;border:1px solid #efd28d}.mode-free{background:#e9f9f2;border-color:#8ad2b5}.mode-cards{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mode-card{border:2px solid var(--line);border-radius:18px;padding:16px;background:#fff;text-align:start}.mode-card.selected{border-color:var(--p);box-shadow:0 0 0 3px #5b4bd822}.mode-card[disabled]{opacity:.55}.mode-badge{display:inline-block;border-radius:999px;padding:4px 9px;font-weight:900;background:#dff5eb;color:#08704c}.mode-badge.advanced{background:#eeeaff;color:#4d3cc4}.teacher-status{display:flex;align-items:center;gap:.7rem;background:#f3f0ff;border-radius:15px;padding:.8rem;font-weight:850}.teacher-orb{width:15px;height:15px;border-radius:50%;background:#5b4bd8}.teacher-status[data-state=listening] .teacher-orb{background:#168b65;animation:pulse .8s infinite}.teacher-controls,.answer-buttons,.report-filters{display:flex;gap:7px;flex-wrap:wrap}.teacher-progress{display:grid;grid-template-columns:repeat(9,1fr);gap:3px}.teacher-progress span{height:7px;background:#ddd;border-radius:9px}.teacher-progress .done{background:#5b4bd8}.teacher-transcript{max-height:155px;overflow:auto;border:1px solid var(--line);border-radius:13px;padding:.65rem}.teacher-report-row{display:grid;gap:.25rem;border:1px solid var(--line);border-radius:14px;padding:.8rem;margin:.5rem 0}.teacher-report-row small{color:var(--muted)}@keyframes pulse{50%{transform:scale(1.35)}}@media(max-width:600px){.mode-cards{grid-template-columns:1fr}}`;document.head.append(s)}
function modal(id,title,html){const m=document.createElement('div');m.className='modal';m.id=id;m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.innerHTML=`<article class="panel"><div class="panelhead"><h2>${title}</h2><button class="close" data-close aria-label="סגירה">×</button></div>${html}</article>`;document.body.append(m)}
function build(){modal('teacherSettings','הגדרות מורים קוליים',`<form id="teacherSettingsForm" class="teacher-settings"><h3>סוג המורה</h3><label>ברירת מחדל<select name="defaultMode"><option value="free">מורה חינמי</option><option value="advanced">מורה AI מתקדם</option></select></label><label><input type="checkbox" name="chooseBeforeLesson"> בחירה לפני כל שיעור</label><label><input type="checkbox" name="childMaySwitch"> הילד/ה רשאי/ת להחליף מצב</label><label><input type="checkbox" name="allowedFree"> לאפשר מורה חינמי</label><label><input type="checkbox" name="allowedAdvanced"> לאפשר מורה AI מתקדם</label><div class="mode-note mode-free"><strong>מורה חינמי — חינם</strong><br>פועל בדפדפן לפי מערך השיעור. אינו דורש API, חיוב או Cloud Functions.</div><div class="teacher-warning"><strong>מורה AI מתקדם</strong><br>שיחה גמישה והסברים מותאמים. השימוש במורה AI מתקדם עשוי להיות כרוך בתשלום לפי שימוש. מנוי ChatGPT Plus אינו כולל שימוש ב־API.</div><label><input type="checkbox" name="advancedConsent"> אני מאשר/ת במפורש עיבוד קולי במורה המתקדם</label><label><input type="checkbox" name="microphoneEnabled"> לאפשר מיקרופון</label><label><input type="checkbox" name="hebrewHelp"> לאפשר עזרה בעברית</label><label><input type="checkbox" name="retainTranscript"> לשמור תמליל טקסט</label><label>דקות חינמיות ביום<input type="number" name="freeDailyMinutes" min="1" max="180"></label><label>דקות AI מתקדם ביום<input type="number" name="advancedDailyMinutes" min="1" max="60"></label><label>דקות AI מתקדם בחודש<input type="number" name="monthlyAdvancedMinutes" min="1" max="2000"></label><div class="teacher-controls"><button class="primary" type="submit">שמירה</button><button class="danger" type="button" id="deleteTeacherTranscripts">מחיקת תמלילים</button></div></form>`);
modal('teacherPreflight','בחירת מורה לשיעור',`<div id="teacherPreflightBody"></div>`);
modal('teacherSession','המורה הקולי',`<div class="teacher-stage"><div class="teacher-progress" id="teacherProgress"></div><div class="teacher-status" id="teacherStatus" data-state="idle"><span class="teacher-orb"></span><span id="teacherStatusText">מוכן</span></div><h3 id="teacherPhase"></h3><p id="teacherInstruction"></p><div class="teacher-transcript" id="teacherTranscript" aria-live="polite"></div><div class="answer-buttons" id="teacherAnswers"></div><div class="teacher-controls"><button class="btn" id="teacherMute">השתקה</button><button class="btn" id="teacherRepeat">חזרה</button><button class="btn" id="teacherHebrew">עזרה בעברית</button><button class="btn" id="teacherPause">השהיה</button><button class="danger" id="teacherEnd">סיום</button></div></div>`);
modal('teacherAchievement','כל הכבוד!',`<div id="teacherAchievementBody"></div>`);wire()}
function sync(){settings={...Core.DEFAULTS,...(window.EAApp.getData().settings?.teacherAI||{})};if(!settings.allowedFree)settings.allowedFree=true;return settings}
function entrypoints(){const head=$('#lessonModal .panelhead');if(head&&!$('#teacherStartBtn')){const b=document.createElement('button');b.id='teacherStartBtn';b.className='teacher-launch';b.textContent='🎙️ שיעור עם מורה קולי';b.onclick=openPreflight;head.append(b)}const a=$('#accountBtn');if(a&&!$('#teacherSettingsBtn')){const b=document.createElement('button');b.id='teacherSettingsBtn';b.className='teacher-launch';b.textContent='🎙️ סוג המורה';b.onclick=openSettings;a.after(b)}const p=$('.privacy');if(p&&!$('#teacherPrivacyNote')){const n=document.createElement('p');n.id='teacherPrivacyNote';n.textContent='המורה החינמי מעבד דיבור בדפדפן ואינו קורא לשירות בתשלום. במורה המתקדם בלבד, ולאחר אישור הורה, קול נשלח לעיבוד בזמן אמת. הקלטת קול גולמית אינה נשמרת.';p.append(n)}}
function openSettings(){sync();const f=$('#teacherSettingsForm');Object.entries(settings).forEach(([k,v])=>{const x=f.elements[k];if(!x)return;x.type==='checkbox'?x.checked=!!v:x.value=v});window.EAApp.openModal('#teacherSettings')}
function wire(){const f=$('#teacherSettingsForm');f.onsubmit=e=>{e.preventDefault();const out={};for(const k of Object.keys(Core.DEFAULTS)){const x=f.elements[k];if(x)out[k]=x.type==='checkbox'?x.checked:x.type==='number'?Number(x.value):x.value}if(!out.allowedAdvanced){out.defaultMode='free';out.advancedConsent=false}settings=window.EAApp.updateTeacherSettings(out);window.EAApp.showToast('הגדרות המורים נשמרו');window.EAApp.closeModal($('#teacherSettings'))};$('#deleteTeacherTranscripts').onclick=deleteTranscripts;$('#teacherMute').onclick=()=>{muted=!muted;micStream?.getAudioTracks().forEach(t=>t.enabled=!muted);recognition?.abort();status(muted?'muted':'idle',muted?'המיקרופון מושתק':'מוכן')};$('#teacherRepeat').onclick=speakCurrent;$('#teacherHebrew').onclick=()=>{hebrewUses++;const i=instruction();speak(i.he,'he-IL')};$('#teacherPause').onclick=()=>{paused=!paused;speechSynthesis.cancel();recognition?.abort();status('paused',paused?'מושהה':'מוכן')};$('#teacherEnd').onclick=()=>finish('parent-ended')}
function deleteTranscripts(){const d=window.EAApp.getData();d.profiles=d.profiles.map(x=>({...x,p:{...x.p,teacherSessions:(x.p.teacherSessions||[]).map(s=>({...s,transcript:[]}))}}));window.EAApp.applySyncedData(d);window.EAApp.showToast('התמלילים נמחקו')}
function openPreflight(){sync();context=window.EAApp.getLessonContext();if(!context)return window.EAApp.showToast('פתחו שיעור תחילה');shared=Core.sharedContext(context);selectedMode=settings.chooseBeforeLesson?(settings.defaultMode||'free'):settings.defaultMode||'free';if(selectedMode==='advanced'&&!settings.allowedAdvanced)selectedMode='free';renderPreflight();window.EAApp.openModal('#teacherPreflight')}
function modeCard(mode,title,badge,desc,disabled=false){return `<button class="mode-card${selectedMode===mode?' selected':''}" data-mode="${mode}" ${disabled?'disabled':''}><span class="mode-badge ${mode==='advanced'?'advanced':''}">${badge}</span><h3>${title}</h3><p>${desc}</p></button>`}
function renderPreflight(message=''){const lesson=context.lesson,advanced=Core.advancedAvailable(settings,teacherAIConfig,navigator.onLine),choose=settings.chooseBeforeLesson&&settings.childMaySwitch;$('#teacherPreflightBody').innerHTML=`${message?`<div class="teacher-warning">${message}</div>`:''}<p><strong>ילד/ה:</strong> ${esc(context.child.name)}</p><p><strong>שיעור:</strong> ${esc(lesson.titleHe||lesson.title)}</p><p><strong>מטרת למידה:</strong> ${esc(lesson.descriptionHe||lesson.description)}</p><p><strong>משך משוער:</strong> 8–12 דקות</p><p><strong>מיקרופון:</strong> ${settings.microphoneEnabled?'מורשה בהגדרות':'חסום בהגדרות'} • <strong>חיבור:</strong> ${navigator.onLine?'מחובר':'לא מקוון'}</p><div class="mode-cards">${modeCard('free','מורה חינמי','חינם','ללא תשלום • עובד לפי מערך השיעור • מתאים לתרגול מובנה',!settings.allowedFree)}${modeCard('advanced','מורה AI מתקדם',advanced.ok?'AI מתקדם':'לא הוגדר','שיחה גמישה יותר • הסברים מותאמים • עשוי להיות כרוך בתשלום',!settings.allowedAdvanced||!choose)}</div><p><strong>המצב שנבחר:</strong> ${selectedMode==='advanced'?'מורה AI מתקדם':'מורה חינמי'}</p><button class="primary" id="teacherBegin">התחלת השיעור</button>`;$('#teacherPreflightBody').querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(!choose&&b.dataset.mode!==settings.defaultMode)return;if(b.dataset.mode==='advanced'&&!settings.allowedAdvanced)return;selectedMode=b.dataset.mode;renderPreflight()});$('#teacherBegin').onclick=start}
async function start(){if(!settings.microphoneEnabled)return window.EAApp.showToast('המיקרופון חסום בהגדרות ההורה');const used=minutesToday(selectedMode),limit=selectedMode==='advanced'?settings.advancedDailyMinutes:settings.freeDailyMinutes;if(used>=limit)return selectedMode==='advanced'?fallback('usage-limit'):window.EAApp.showToast('מגבלת הדקות היומית של המורה החינמי הושגה');if(selectedMode==='advanced'){const check=Core.advancedAvailable(settings,teacherAIConfig,navigator.onLine);if(!check.ok)return fallback(check.reason)}window.EAApp.closeModal($('#teacherPreflight'));window.EAApp.openModal('#teacherSession');reset();if(selectedMode==='advanced')startAdvanced().catch(e=>fallback(e.message,true));else startFree()}
function minutesToday(mode){const today=new Date().toISOString().slice(0,10),profile=window.EAApp.getData().profiles.find(p=>p.id===context.child.id);return(profile?.p.teacherSessions||[]).filter(s=>(s.teacherMode||'free')===mode&&String(s.endedAt||'').startsWith(today)).reduce((n,s)=>n+(Number(s.durationSeconds)||0)/60,0)}
function fallback(reason,during=false){selectedMode='free';const map={'parent-blocked':'המורה המתקדם נחסם בהגדרות ההורה.','consent-required':'נדרש אישור הורה למורה המתקדם.','not-configured':'המורה המתקדם לא הוגדר.','offline':'אין חיבור לרשת.','usage-limit':'מגבלת שימוש הושגה.'};const msg=`${map[reason]||'המורה המתקדם אינו זמין כרגע.'} <button class="primary" id="useFree">לעבור למורה החינמי</button>`;if(during){window.EAApp.closeModal($('#teacherSession'));window.EAApp.openModal('#teacherPreflight')}renderPreflight(msg);$('#useFree').onclick=()=>{selectedMode='free';renderPreflight('אפשר להמשיך ללא תשלום עם המורה החינמי.')};window.EAApp.openModal('#teacherPreflight')}
function reset(){phase=0;startedAt=Date.now();transcript=[];words=[];review=[];correct=0;retries=0;hebrewUses=0;paused=false;muted=false;sessionId=crypto.randomUUID?.()||`teacher-${Date.now()}`;$('#teacherTranscript').replaceChildren();renderPhase()}
function renderPhase(){const box=$('#teacherProgress');box.replaceChildren(...PHASES.map((_,i)=>{const s=document.createElement('span');if(i<=phase)s.className='done';return s}));$('#teacherPhase').textContent=`שלב: ${PHASE_HE[PHASES[phase]]}`}
function status(state,text){$('#teacherStatus').dataset.state=state;$('#teacherStatusText').textContent=text}
function line(who,text){transcript.push({id:crypto.randomUUID?.()||String(Date.now()),at:new Date().toISOString(),who,text:String(text).slice(0,500)});const p=document.createElement('p');p.textContent=`${who}: ${text}`;$('#teacherTranscript').append(p)}
function instruction(){const phrases=shared.lesson.phrases||[],p=phrases[Math.min(Math.max(0,phase-2),phrases.length-1)]||phrases[0]||{english:shared.lesson.title,hebrew:''},q=shared.lesson.quiz?.[0];return[{en:`Hello ${context.child.name}! Today we will learn ${shared.lesson.title}.`,he:`שלום ${context.child.name}! היום נלמד ${shared.lesson.titleHe||shared.lesson.title}.`,listen:false},{en:'Tell me one English word you remember.',he:'אמרו מילה אחת שאתם זוכרים באנגלית.',listen:true,expected:[]},{en:`Listen: ${p.english}`,he:p.hebrew||'הקשיבו למילה.',listen:false},{en:`Please repeat: ${p.english}`,he:'חזרו אחרי המורה.',listen:true,expected:[p.english]},{en:q?.question||`What does ${p.english} mean?`,he:q?.questionHe||'מה פירוש המשפט?',listen:true,expected:q?[q.options[q.answer]]:[p.english]},{en:`Say a short sentence using: ${p.english}`,he:'אמרו משפט קצר עם הביטוי.',listen:true,expected:[p.english]},{en:`Let us review: ${p.english}`,he:'חזרה קצרה על מה שלמדנו.',listen:true,expected:[p.english]},{en:`Great work. You practiced ${words.length||phrases.length} phrases.`,he:'כל הכבוד! סיימנו את הסיכום.',listen:false},{en:`Goodbye ${context.child.name}! Great effort!`,he:'להתראות וכל הכבוד!',listen:false}][phase]}
function speak(text,lang='en-US',after){status('speaking','המורה מדבר');line('המורה',text);const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.85;u.onend=()=>{status('idle','מוכן');after?.()};speechSynthesis.cancel();speechSynthesis.speak(u)}
function speakCurrent(){if(paused)return;const i=instruction();$('#teacherInstruction').textContent=settings.hebrewHelp?`${i.en} — ${i.he}`:i.en;speak(i.en,'en-US',()=>{if(i.listen)listen(i);else setTimeout(nextPhase,350)})}
function startFree(){selectedMode='free';speakCurrent()}
function listen(i){if(muted||paused)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return showAnswers(i);recognition=new SR();recognition.lang='en-US';recognition.interimResults=false;recognition.onstart=()=>status('listening','מקשיב/ה עכשיו');recognition.onresult=e=>evaluate(e.results[0][0].transcript,i);recognition.onerror=e=>{if(e.error==='not-allowed')showAnswers(i,'המיקרופון לא אושר. אפשר לענות בלחיצה.');else showAnswers(i,'לא הצלחנו לשמוע. אפשר לבחור תשובה.')};recognition.onend=()=>{recognition=null};try{recognition.start()}catch{showAnswers(i)}}
function showAnswers(i,note='זיהוי דיבור אינו זמין בדפדפן הזה. אפשר לענות בלחיצה.'){status('idle',note);const box=$('#teacherAnswers');box.replaceChildren();const q=shared.lesson.quiz?.[0],opts=q?.options||[i.expected?.[0]||'I tried','Repeat please','I need help'];opts.slice(0,3).forEach(v=>{const b=document.createElement('button');b.className='option';b.textContent=v;b.onclick=()=>evaluate(v,i);box.append(b)})}
function evaluate(heard,i){recognition?.stop();$('#teacherAnswers').replaceChildren();line(context.child.name,heard);const expected=i.expected||[],ok=!expected.length||Core.answerMatches(heard,expected);if(ok){correct++;if(expected[0])words.push(expected[0]);speak('Great job!','en-US',nextPhase)}else{retries++;if(expected[0])review.push(expected[0]);speak(retries%2?'Almost. Try once more.':'Good try. Let us continue.','en-US',retries%2?()=>listen(i):nextPhase)}}
function nextPhase(){phase++;renderPhase();if(phase>=PHASES.length-1){speakCurrent();setTimeout(()=>finish('completed'),1300)}else speakCurrent()}
async function startAdvanced(){const token=await window.EASync?.getIdToken();if(!token)throw new Error('not-configured');micStream=await navigator.mediaDevices.getUserMedia({audio:true});const r=await backend('session',{context:{...context,sharedLesson:shared},limits:{dailyMinutes:settings.advancedDailyMinutes,monthlyMinutes:settings.monthlyAdvancedMinutes},hebrewHelp:settings.hebrewHelp,retainTranscript:settings.retainTranscript});sessionId=r.sessionId;pc=new RTCPeerConnection();const audio=document.createElement('audio');audio.autoplay=true;pc.ontrack=e=>audio.srcObject=e.streams[0];micStream.getTracks().forEach(t=>pc.addTrack(t,micStream));dc=pc.createDataChannel('oai-events');dc.onmessage=e=>{try{const v=JSON.parse(e.data);if(v.type==='response.audio_transcript.done')line('המורה',v.transcript);if(v.type==='conversation.item.input_audio_transcription.completed')line(context.child.name,v.transcript)}catch{}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);const sdp=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',headers:{Authorization:`Bearer ${r.clientSecret}`,'Content-Type':'application/sdp'},body:offer.sdp});if(!sdp.ok)throw new Error('backend');await pc.setRemoteDescription({type:'answer',sdp:await sdp.text()});status('listening','המורה המתקדם מחובר')}
async function backend(action,payload={}){const token=await window.EASync?.getIdToken();const r=await fetch(teacherAIConfig.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action,...payload})});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||'backend');return out}
function finish(reason){speechSynthesis.cancel();recognition?.abort();dc?.close();pc?.close();micStream?.getTracks().forEach(t=>t.stop());const end=new Date().toISOString(),summary=Core.sessionReport({id:sessionId,teacherMode:selectedMode,lessonId:shared.lessonId,lessonTitle:shared.lesson.titleHe||shared.lesson.title,startedAt:new Date(startedAt).toISOString(),endedAt:end,durationSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000)),wordsPracticed:words,correctAnswers:correct,retries,hebrewHelpCount:hebrewUses,wordsNeedingReview:review,completionStatus:reason==='completed'?'completed':'partial',transcript:settings.retainTranscript?transcript:[],apiUsage:selectedMode==='advanced'?{status:'approximate-unavailable'}:null});window.EAApp.recordTeacherSession(summary);if(selectedMode==='advanced')backend('complete',{sessionId,summary}).catch(()=>{});window.EAApp.closeModal($('#teacherSession'));$('#teacherAchievementBody').innerHTML=`<div class="celebrate"><div class="trophy">🏆</div><h2>כל הכבוד, ${esc(context.child.name)}!</h2><p>${selectedMode==='advanced'?'מורה AI מתקדם':'מורה חינמי'} • ${correct} תשובות נכונות • ${retries} ניסיונות חוזרים</p><p>מילים לתרגול: ${esc(review.join(', ')||'אין הערה מיוחדת')}</p></div>`;window.EAApp.openModal('#teacherAchievement')}
function renderReports(){const body=$('#parentBody');if(!body||$('#teacherReports'))return;const wrap=document.createElement('section');wrap.id='teacherReports';wrap.innerHTML='<h3>דוחות מורים קוליים</h3><div class="report-filters"><button class="btn" data-filter="all">כל המפגשים</button><button class="btn" data-filter="free">מורה חינמי</button><button class="btn" data-filter="advanced">מורה AI מתקדם</button></div><div id="teacherReportRows"></div>';body.append(wrap);const draw=filter=>{const rows=$('#teacherReportRows');rows.replaceChildren();const sessions=window.EAApp.getData().profiles.flatMap(p=>(p.p.teacherSessions||[]).map(s=>({...s,child:p.name}))).filter(s=>filter==='all'||s.teacherMode===filter).sort((a,b)=>(b.endedAt||'').localeCompare(a.endedAt||''));if(!sessions.length)rows.textContent='עדיין אין מפגשי מורה קולי.';sessions.forEach(s=>{const r=document.createElement('div');r.className='teacher-report-row';r.innerHTML=`<strong>${esc(s.lessonTitle||s.lessonId)} — ${s.teacherMode==='advanced'?'AI מתקדם':'חינם'}</strong><small>${esc(s.child)} • ${new Date(s.endedAt).toLocaleString('he-IL')} • ${Math.ceil((s.durationSeconds||0)/60)} דקות</small><span>מילים: ${esc((s.wordsPracticed||s.phrases||[]).join(', ')||'—')} • נכונות: ${s.correctAnswers||0} • ניסיונות: ${s.retries||0} • עזרה בעברית: ${s.hebrewHelpCount||0}</span><span>לחזרה: ${esc((s.wordsNeedingReview||s.mistakes||[]).join(', ')||'—')} • מצב: ${s.completionStatus==='partial'?'חלקי':'הושלם'}</span>`;rows.append(r)})};wrap.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>draw(b.dataset.filter));draw('all')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

await ready;styles();build();entrypoints();sync();new MutationObserver(()=>{entrypoints();renderReports()}).observe(document.body,{childList:true,subtree:true});
