const test=require('node:test'),assert=require('node:assert/strict');
const Adaptive=require('../../adaptive-learning'),content=require('../../content.json');
const ev=(id,at='2026-07-01',lessonId='l1',extra={})=>({id,at,lessonId,skill:'vocabulary',correct:true,hintUsed:false,retries:0,recognitionConfidence:.95,...extra});
function feed(state,events){let r;for(const e of events){r=Adaptive.recordEvidence(state,e);state=r.state}return r}
test('one good answer never promotes',()=>assert.equal(Adaptive.recordEvidence(null,ev('a')).state.skills.vocabulary.level,1));
test('promotion requires several lessons, days and delayed review and rises only once',()=>{let s=Adaptive.blankState();s.skills.vocabulary.confidence=.7;const r=feed(s,[ev('a'),ev('b'),ev('c','2026-07-02','l2'),ev('d','2026-07-03','l2',{delayedReview:true})]);assert.equal(r.state.skills.vocabulary.level,2);assert.equal(Adaptive.recordEvidence(r.state,ev('e','2026-07-03T01:00:00Z','l2')).state.skills.vocabulary.level,2)});
test('hints, manual, skipped, fuzzy and immediate repeats cannot falsely promote',()=>{let s=Adaptive.blankState();s.skills.vocabulary.confidence=.9;const r=feed(s,[ev('a',undefined,undefined,{hintUsed:true}),ev('b','2026-07-02','l2',{manual:true}),ev('c','2026-07-02','l2',{skipped:true}),ev('d','2026-07-03','l3',{broadFuzzy:true}),ev('e','2026-07-04','l4',{immediateRepeat:true,delayedReview:true})]);assert.equal(r.state.skills.vocabulary.level,1);assert.equal(r.metrics.activities,1)});
test('low recognition confidence is not evidence',()=>assert.equal(Adaptive.metrics([ev('a',undefined,undefined,{recognitionConfidence:.2})]).activities,0));
test('good evidence schedules review and failed review does not promote',()=>{let s=Adaptive.blankState();s.skills.vocabulary.confidence=.9;let r=feed(s,[ev('a'),ev('b'),ev('c','2026-07-02','l2')]);assert.ok(r.state.skills.vocabulary.pendingReview);r=Adaptive.recordEvidence(r.state,ev('d','2026-07-03','l2',{correct:false,delayedReview:true}));assert.equal(r.state.skills.vocabulary.level,1)});
test('struggle simplifies first and lowers stored level only across sessions',()=>{let s=Adaptive.manualSet(null,'vocabulary',4),r=feed(s,[ev('a',undefined,undefined,{correct:false}),ev('b',undefined,undefined,{correct:false}),ev('c',undefined,undefined,{correct:false})]);assert.equal(r.adjustment,'easier');assert.equal(r.state.skills.vocabulary.level,4);r=feed(r.state,[ev('d','2026-07-02','l2',{correct:false}),ev('e','2026-07-02','l2',{correct:false}),ev('f','2026-07-03','l3',{correct:false})]);assert.equal(r.state.skills.vocabulary.level,3)});
test('parent maximum and manual changes are respected and logged',()=>{let s=Adaptive.setControls(null,{maxLevel:3});s=Adaptive.manualSet(s,'reading',9);assert.equal(s.skills.reading.level,3);assert.equal(s.manualLog.length,1)});
test('migration retains old data and adds all skills',()=>{const s=Adaptive.migrate({skills:{reading:{level:5,evidence:[{id:'old'}]}}});assert.equal(s.skills.reading.level,5);assert.equal(s.skills.reading.evidence[0].id,'old');assert.equal(Object.keys(s.skills).length,7)});
test('placement is bounded and has limited confidence',()=>{const s=Adaptive.placementEstimate([{skill:'reading',level:1,correct:true},{skill:'reading',level:3,correct:true}]);assert.equal(s.skills.reading.level,3);assert.ok(s.skills.reading.confidence<.7)});
test('all 110 activities have adaptive mapping metadata',()=>{const xs=content.lessons.flatMap(l=>[...(l.phrases||[]),...(l.quiz||[])]);assert.equal(xs.length,110);for(const x of xs){const m=Adaptive.mapExercise(x,{phase:x.question?'comprehension':'listen-repeat',level:5});assert.ok(Adaptive.SKILLS.includes(m.skill));assert.ok(m.expectedSupport);assert.ok(m.promotionEvidence)}});
test('session adaptation reacts in both directions',()=>{assert.equal(Adaptive.sessionAdaptation([ev('a'),ev('b'),ev('c')]).direction,'harder');assert.equal(Adaptive.sessionAdaptation([{correct:false},{correct:false},{correct:true}]).direction,'easier')});
